//! Each branch's settings, from its [branch.<name>] table (and each custom
//! edge's, from its [edge.<name>]).
//!
//! Generated by `bonsai sync` from bonsai.toml and src/messages.rs. Don't edit
//! it: change those, then run `bonsai sync` (every bonsai command that changes
//! the graph runs it for you).
#![allow(dead_code)]
