//! The trunk: the tree's shared vocabulary, and the handle branches grow from.
//!
//! Branches never reach into one another. Instead they release *nutrients*
//! (events / messages / state) into the sap and tap the ones they care about.
//! Each nutrient flows along its own path (see `sap.rs`, generated by bonsai), so
//! a branch wakes only for what it taps and one busy path can't starve another.

// The generated sap (src/sap.rs) is a child of the trunk, so the payload types
// you use in `Nutrient` resolve there exactly as they do here.
#[rustfmt::skip] // generated by bonsai — `bonsai sync` rewrites it
#[path = "sap.rs"]
pub mod sap;

pub use sap::Sap;

/// A nutrient passed between branches. Add your own variants as the device
/// grows (`bonsai feed`) — this enum is the shared vocabulary of the tree.
///
/// Each path carries only its own variant's payload, so a big variant costs RAM
/// only on its own path; `bonsai feed` notes how much when one is large.
#[derive(Clone)]
pub enum Nutrient {
    /// Released by the pulse each tick (see `pulse.rs`).
    Beat,
    // bonsai:nutrient
}

/// Handed to every branch's `start()` by the trunk (`main.rs`).
pub struct Trunk {
    sap: Sap,
}

impl Trunk {
    pub fn new() -> Self {
        Trunk { sap: Sap }
    }

    /// The release side of the sap, for a branch that *feeds* nutrients.
    /// (A branch that *taps* them claims `sap::<branch>::Taps::new()` instead.)
    pub fn sap(&self) -> Sap {
        self.sap
    }
}
