#![no_std]
#![no_main]

//! {{project-name}} — device firmware for {{board}} (esp32-{{chip}}).
//! Generated by bonsai.
//!
//! This file is the *trunk*: it brings up the hardware, starts the built-in
//! pulse (the tree's cycle of life — see `pulse.rs`), then your branches. It's
//! also where hardware is handed out. Grow with `bonsai branch <name>`.

mod branches;
mod pulse;
mod trunk;
{% if wifi %}mod wifi;
{% endif %}
use embassy_executor::Spawner;
use embassy_time::{Duration, Timer};
use esp_backtrace as _; // panic handler (prints over defmt)
use esp_hal::clock::CpuClock;
use esp_hal::timer::timg::TimerGroup;
use esp_println as _; // routes defmt over espflash
use trunk::Trunk;
use trunk::sap; // the generated sap lives under the trunk (src/sap.rs)

// Required by the ESP-IDF second-stage bootloader to recognise the app image.
esp_bootloader_esp_idf::esp_app_desc!();

#[esp_rtos::main]
async fn main(spawner: Spawner) -> ! {
    let config = esp_hal::Config::default().with_cpu_clock(CpuClock::max());
    let peripherals = esp_hal::init(config);
{% if wifi %}
    // The WiFi driver allocates its buffers; this is its heap.
    esp_alloc::heap_allocator!(size: 72 * 1024);
{% endif %}
    // Start esp-rtos so Embassy's executor and time driver run.
    let timg0 = TimerGroup::new(peripherals.TIMG0);
    esp_rtos::start(timg0.timer0, peripherals.FROM_CPU_INTR0);

    let trunk = Trunk::new();

    // The pulse: bonsai's built-in cycle of life — a heartbeat feeding the sap
    // and a monitor logging each beat. Always running, proof of life.
    pulse::start(&spawner, &trunk);
{% if wifi %}
    // WiFi: joins the network set in .cargo/config.toml. `net` is the network
    // stack; hand it to branches that open sockets.
    let net = wifi::start(&spawner, peripherals.WIFI);
    let _ = net; // placeholder: delete once a branch uses the network
{% endif %}
    // Your subsystems. `bonsai branch <name>` wires them in here. Hand each the
    // hardware it owns (e.g. a GPIO from `peripherals`).
    // bonsai:start

    // The trunk's own work is done; idle while the branches run.
    loop {
        Timer::after(Duration::from_secs(3600)).await;
    }
}
