//! The sap — how nutrients flow between branches. GENERATED by bonsai from the
//! tree's wiring: every wiring command (branch/snip/feed/starve/tap/untap/
//! release/unrelease/path/sync) rewrites this file, so don't edit it by hand.
//! To change a path's shape or capacity, run `bonsai path <Nutrient> …` (or edit
//! `bonsai.toml`, then `bonsai sync`).
//!
//! Branches never touch the channels directly. A branch that feeds nutrients
//! holds a `Sap` (`trunk.sap()`) and calls `sap.release(..)`; one that taps
//! them owns its generated `Taps` (`sap::<branch>::Taps::new()`) and awaits
//! `taps.next()`, which wakes only for the nutrients that branch taps.
//!
//! layout: paths — one channel per nutrient.
//!
//!   Beat  broadcast  cap 2    pulse → pulse

#![allow(dead_code, unused_imports, clippy::new_without_default)]

use core::future::{Future, poll_fn};
use core::pin::{Pin, pin};
use core::task::{Context, Poll};

use embassy_sync::blocking_mutex::raw::CriticalSectionRawMutex as M;
use embassy_sync::channel::{Channel, SendFuture, TrySendError};
use embassy_sync::pubsub::{PubSubChannel, Subscriber, WaitResult};
use embassy_sync::watch::{self, Watch, WatchBehavior};

// The trunk's own imports too, so payload types written in trunk.rs resolve
// here (the sap is a child module of the trunk).
use super::*;
use crate::trunk::Nutrient;

// ── slots: each path holds only its own payload ────────────────────────────

fn beat_nutrient(_: ()) -> Nutrient {
    Nutrient::Beat
}

// ── paths: one per nutrient ────────────────────────────────────────────────

/// `Beat`: broadcast, 2 queued, 1 tapper.
static BEAT_PATH: PubSubChannel<M, (), 2, 1, 0> = PubSubChannel::new();

/// The release side of the sap: zero-sized and `Copy`, so hand one to every
/// branch that feeds nutrients (`trunk.sap()`).
#[derive(Clone, Copy)]
pub struct Sap;

impl Sap {
    /// Release a nutrient onto its path; `.await` the result. Broadcast and
    /// state paths take it at once and never wait (a broadcast tapper that falls
    /// behind loses its oldest); a directed path waits while it's full — see
    /// `try_release` for a version that doesn't.
    pub fn release(&self, n: Nutrient) -> Release {
        match n {
            Nutrient::Beat => {
                BEAT_PATH.immediate_publisher().publish_immediate(());
                Release(Pending::Done)
            }
        }
    }

    /// Like `release`, but never waits: a full directed path hands `n` back.
    pub fn try_release(&self, n: Nutrient) -> Result<(), Nutrient> {
        match n {
            Nutrient::Beat => {
                BEAT_PATH.immediate_publisher().publish_immediate(());
                Ok(())
            }
        }
    }
}

/// What `sap.release(..)` returns: already done for a broadcast or state path,
/// or a directed path's pending send. It holds only that path's slot — never a
/// whole `Nutrient` — so a task awaiting a release stays small.
#[must_use = "a directed release only happens once awaited"]
pub struct Release(Pending);

enum Pending {
    Done,
}

impl Future for Release {
    type Output = ();

    fn poll(self: Pin<&mut Self>, cx: &mut Context<'_>) -> Poll<()> {
        match &mut self.get_mut().0 {
            Pending::Done => {
                let _ = cx;
                Poll::Ready(())
            }
        }
    }
}

/// Queue depth per path — `(nutrient, queued, capacity)` — for diagnostics.
pub fn depths() -> [(&'static str, usize, usize); 1] {
    [
        ("Beat", BEAT_PATH.len(), 2),
    ]
}

// ── taps: one set per branch ───────────────────────────────────────────────

/// What `pulse` taps: Beat.
pub mod pulse {
    use super::*;

    const WHO: &str = "pulse";

    pub struct Taps {
        lagged: u64,
        streak: u8,
        beat_tap: Subscriber<'static, M, (), 2, 1, 0>,
    }

    impl Taps {
        /// Claim this branch's taps. Call once, at startup.
        pub fn new() -> Self {
            Self {
                lagged: 0,
                streak: 0,
                beat_tap: BEAT_PATH.subscriber().unwrap_or_else(|_| miscounted()),
            }
        }

        /// Nutrients lost on broadcast paths because this branch fell behind.
        pub fn lagged(&self) -> u64 {
            self.lagged
        }

        /// Wait for the next nutrient this branch taps. After a burst of
        /// `BURST` back-to-back nutrients it yields to the executor once, so a
        /// flood (or a branch feeding itself) can't starve the other branches.
        pub async fn next(&mut self) -> Nutrient {
            poll_fn(|cx| {
                if self.streak == BURST {
                    self.streak = 0;
                    cx.waker().wake_by_ref();
                    return Poll::Pending;
                }
                let got = poll_broadcast(&mut self.beat_tap, WHO, "Beat", &mut self.lagged, cx).map(beat_nutrient);
                self.streak = if got.is_ready() { self.streak + 1 } else { 0 };
                got
            })
            .await
        }
    }
}

// ── plumbing ───────────────────────────────────────────────────────────────

/// A path ran out of tapper slots. bonsai counts them from the wiring, so this
/// only happens after a hand edit it hasn't seen. (A plain panic, not an
/// `expect`, so no error-formatting code is linked in.)
fn miscounted() -> ! {
    panic!("sap: more taps than bonsai counted — run `bonsai sync`")
}

/// Back-to-back nutrients a branch takes before `next()` yields to the executor.
const BURST: u8 = 32;

/// Called when branch `who` fell behind on a broadcast path and lost `missed`
/// nutrients (they're also counted in its `taps.lagged()`).
fn note_lag(who: &'static str, path: &'static str, missed: u64) {
    // Opt-in (a flood can lag thousands of times): run with BONSAI_SAP_DEBUG set.
    static ON: std::sync::OnceLock<bool> = std::sync::OnceLock::new();
    if *ON.get_or_init(|| std::env::var_os("BONSAI_SAP_DEBUG").is_some()) {
        eprintln!("sap: {who} lagged on {path}, {missed} lost");
    }
}

/// Poll a broadcast subscriber, counting (and skipping past) any lag.
fn poll_broadcast<T: Clone, const CAP: usize, const SUBS: usize, const PUBS: usize>(
    sub: &mut Subscriber<'static, M, T, CAP, SUBS, PUBS>,
    who: &'static str,
    path: &'static str,
    lagged: &mut u64,
    cx: &mut Context<'_>,
) -> Poll<T> {
    loop {
        match pin!(sub.next_message()).poll(cx) {
            Poll::Ready(WaitResult::Message(n)) => return Poll::Ready(n),
            Poll::Ready(WaitResult::Lagged(missed)) => {
                *lagged += missed;
                note_lag(who, path, missed);
            }
            Poll::Pending => return Poll::Pending,
        }
    }
}

/// Poll a fresh future once. The receivers keep their state outside the
/// future, so dropping it after `Pending` loses nothing.
fn poll_once<F: Future>(cx: &mut Context<'_>, fut: F) -> Poll<F::Output> {
    pin!(fut).poll(cx)
}
