//! {{branch_name}} root — carries messages between the outside world and the tree.
//! Generated by `bonsai branch --roots {{branch_name}}` (std trees only).

use embassy_executor::Spawner;
use embassy_futures::select::{Either, select};

use crate::roots::{self, Inbox, Outbox};
use crate::sap::{self, Sap};
#[allow(unused_imports)] // used once you tap or release a nutrient
use crate::trunk::Nutrient;
use crate::trunk::Trunk;

/// TODO: one message from the link. Raw bytes to start; your own type once you decode.
pub type Inbound = Vec<u8>;
/// TODO: one message to the link.
pub type Outbound = Vec<u8>;

/// Launch this root. The trunk calls this once at startup.
pub fn start(spawner: &Spawner, trunk: &Trunk) {
    // TODO: open your link here (a socket, a serial port, a protocol connection).
    let (inbox, outbox) = roots::bridge(
        "{{branch_name}}",
        // TODO: loop on the link's blocking receive and `deliver(msg)` each message.
        move |deliver| {
            let _ = deliver; // placeholder: delete once you deliver something
        },
        // TODO: write `msg` to the link. Blocking is fine: this runs on its own thread.
        move |msg: Outbound| drop(msg),
    );
    // Fails only if `run` is already running. A fixed message links no formatting code.
    spawner.spawn(
        run(sap::{{branch_name}}::Taps::new(), trunk.sap(), inbox, outbox)
            .unwrap_or_else(|_| panic!("{{branch_name}}: run already running")),
    );
}

/// Moves messages both ways: link → nutrients, nutrients → link.
#[embassy_executor::task]
async fn run(
    mut taps: sap::{{branch_name}}::Taps,
    sap: Sap,
    inbox: Inbox<Inbound>,
    outbox: Outbox<Outbound>,
) {
    loop {
        // Wait for whichever comes first: a message from the link, or a nutrient.
        match select(inbox.next(), taps.next()).await {
            Either::First(msg) => {
                // TODO: decode `msg`, then release what it carries.
                let _ = &msg;
                // release nutrients with `bonsai release {{branch_name}} <Nutrient>`
                // bonsai:emit
                let _ = &sap; // placeholder: delete once you release something
            }
            Either::Second(nutrient) => {
                // until it taps more nutrients
                #[allow(clippy::single_match, clippy::match_single_binding)]
                match nutrient {
                    // TODO: encode each tapped nutrient, then `outbox.send(msg)`.
                    // tap nutrients with `bonsai tap {{branch_name}} <Nutrient>`
                    // bonsai:nutrient-arm
                    #[allow(unreachable_patterns)]
                    _ => {}
                }
                let _ = &outbox; // placeholder: delete once you send something
            }
        }
    }
}
