//! {{branch_name}} branch — a subsystem of this device.
//! Generated by `bonsai branch --produces {{branch_name}}`.

use embassy_executor::Spawner;

use crate::sap::Sap;
#[allow(unused_imports)] // used once you `bonsai release` a nutrient
use crate::trunk::Nutrient;
use crate::trunk::Trunk;

/// Launch this branch. The trunk calls this once at startup.
pub fn start(spawner: &Spawner, trunk: &Trunk) {
    // Fails only if `run` is already running. A fixed message links no formatting code.
    spawner
        .spawn(run(trunk.sap()).unwrap_or_else(|_| panic!("{{branch_name}}: run already running")));
}

/// Sends nutrients with `sap.release(..).await`. Only a full directed path
/// makes it wait; `sap.try_release(..)` never does.
#[embassy_executor::task]
async fn run(sap: Sap) {
    loop {
        // TODO: wait for your data: a timer, a pin edge, a driver's `read()`.
        core::future::pending::<()>().await;
        // release nutrients with `bonsai release {{branch_name}} <Nutrient>`
        // bonsai:emit
        let _ = &sap; // placeholder: delete once you release something
    }
}
