//! {{branch_name}} branch — a subsystem of this device.
//! Generated by `bonsai branch {{branch_name}}`.

use embassy_executor::Spawner;

use crate::sap;
use crate::trunk::{Nutrient, Trunk};

/// Launch this branch. The trunk calls this once at startup.
pub fn start(spawner: &Spawner, _trunk: &Trunk) {
    // Fails only if `run` is already running. A fixed message links no formatting code.
    spawner.spawn(
        run(sap::{{branch_name}}::Taps::new())
            .unwrap_or_else(|_| panic!("{{branch_name}}: run already running")),
    );
}

/// Receives the nutrients this branch taps, and only those.
#[embassy_executor::task]
async fn run(mut taps: sap::{{branch_name}}::Taps) {
    loop {
        let nutrient: Nutrient = taps.next().await;
        #[allow(clippy::single_match, clippy::match_single_binding)] // until it taps more nutrients
        match nutrient {
            // tap nutrients with `bonsai tap {{branch_name}} <Nutrient>`
            // bonsai:nutrient-arm
            #[allow(unreachable_patterns)]
            _ => {}
        }
    }
}
