//! {{branch_name}} branch — a subsystem of this device.
//! Generated by `bonsai branch --duplex {{branch_name}}`.

use embassy_executor::Spawner;

use crate::sap::{self, Sap};
use crate::trunk::{Nutrient, Trunk};

/// Launch this branch. The trunk calls this once at startup.
pub fn start(spawner: &Spawner, trunk: &Trunk) {
    // Fails only if `run` is already running. A fixed message links no formatting code.
    spawner.spawn(
        run(sap::{{branch_name}}::Taps::new(), trunk.sap())
            .unwrap_or_else(|_| panic!("{{branch_name}}: run already running")),
    );
}

/// Receives the nutrients this branch taps and releases replies.
#[embassy_executor::task]
async fn run(mut taps: sap::{{branch_name}}::Taps, sap: Sap) {
    loop {
        let nutrient: Nutrient = taps.next().await;
        #[allow(clippy::single_match, clippy::match_single_binding)] // until it taps more nutrients
        match nutrient {
            // tap nutrients with `bonsai tap {{branch_name}} <Nutrient>`
            // bonsai:nutrient-arm
            #[allow(unreachable_patterns)]
            _ => {}
        }
        // TODO: `bonsai release` adds calls here, where they run after every nutrient.
        // Move each into the arm that should reply.
        // bonsai:emit
        let _ = &sap; // placeholder: delete once you release something
    }
}
