#![no_std]
#![no_main]

//! {{project-name}} — device firmware for {{board}} ({{chip}}).
//! Generated by bonsai.
//!
//! This file is the *trunk*: it brings up the hardware, starts the built-in
//! pulse (the tree's cycle of life — see `pulse.rs`), then your branches. It's
//! also where hardware is handed out: a pin belongs to exactly one branch. Grow
//! the device with `bonsai branch <name>`.

mod branches;
mod pulse;
mod trunk;

use defmt_rtt as _; // global defmt logger, over RTT
use embassy_executor::Spawner;
use panic_probe as _; // panic handler that prints through defmt
use trunk::Trunk;
use trunk::sap; // the generated sap lives under the trunk (src/sap.rs)

#[embassy_executor::main(executor = "embassy_rp::executor::Executor", entry = "cortex_m_rt::entry")]
async fn main(spawner: Spawner) {
    // Rename to `p` and hand pins to the branches that need them (e.g. an LED:
    // `Output::new(p.PIN_25, Level::Low)` — GP25 on Pico / Pico 2).
    let _p = embassy_rp::init(Default::default());

    let trunk = Trunk::new();

    // The pulse: bonsai's built-in cycle of life — a heartbeat feeding the sap
    // and a monitor logging each beat. Always running, proof of life.
    pulse::start(&spawner, &trunk);

    // Your subsystems. `bonsai branch <name>` wires them in here.
    // bonsai:start
}
