//! `bonsai doctor`: read-only checks on a tree, each with what's wrong and
//! what to do about it. It writes nothing, installs nothing and connects to
//! nothing: the graph is checked with `graph::check`, generated files against
//! `sync::plan` (what `bonsai sync` would write), tools by looking on PATH.

use std::path::Path;

use crate::sync::{self, Refused};
use crate::tools::{self, Tool};
use crate::tree::{CONFIG, INPUT_ARM, MESSAGE_MARKER, MESSAGES};

/// How a check came out.
#[derive(Debug, Clone, Copy, PartialEq, Eq, PartialOrd, Ord)]
pub enum Status {
    Ok,
    /// Could not run (and why is in the message): neither passed nor failed.
    Skipped,
    Warning,
    Error,
}

impl Status {
    pub fn name(self) -> &'static str {
        match self {
            Status::Ok => "ok",
            Status::Skipped => "skipped",
            Status::Warning => "warning",
            Status::Error => "error",
        }
    }
}

/// One result. `id` names the check and stays the same from run to run;
/// `subject` is what it's about (a branch, a file), when it's about one.
#[derive(Debug, Clone, PartialEq)]
pub struct Finding {
    pub id: &'static str,
    pub status: Status,
    pub subject: Option<String>,
    pub message: String,
    /// What to do about it (None when there's nothing to do).
    pub fix: Option<String>,
}

fn finding(id: &'static str, status: Status, message: impl Into<String>) -> Finding {
    Finding {
        id,
        status,
        subject: None,
        message: message.into(),
        fix: None,
    }
}

impl Finding {
    fn about(mut self, subject: impl Into<String>) -> Self {
        self.subject = Some(subject.into());
        self
    }
    fn fix(mut self, fix: impl Into<String>) -> Self {
        self.fix = Some(fix.into());
        self
    }
}

/// Run every check on the tree at `root`.
pub fn check(root: &Path) -> Vec<Finding> {
    let mut out = Vec::new();
    let cargo = std::fs::read_to_string(root.join("Cargo.toml")).unwrap_or_default();
    if root.join("src/sap.rs").exists() || cargo.contains("embassy-executor") {
        out.push(
            finding(
                "tree",
                Status::Error,
                "an older bonsai's tree (Embassy, src/sap.rs): this bonsai can't work on it",
            )
            .fix("plant a new tree (`bonsai`) and move your code into its branches"),
        );
        return out;
    }
    if !cargo.contains("Generated by bonsai for") || !root.join(CONFIG).is_file() {
        out.push(
            finding(
                "tree",
                Status::Error,
                "not a bonsai tree: no bonsai.toml and Cargo.toml stamp here",
            )
            .fix("run `bonsai doctor` inside a tree, or plant one with `bonsai`"),
        );
        return out;
    }
    let board = crate::parse_board(&cargo).unwrap_or_else(|| "?".to_string());
    out.push(finding(
        "tree",
        Status::Ok,
        format!("a bonsai tree for {board}"),
    ));

    // The graph.
    match sync::read_config(root) {
        Err(e) => {
            out.push(finding("config", Status::Error, e).fix(format!(
                "fix {CONFIG} where it says, then run `bonsai doctor` again"
            )));
            for id in ["graph", "sources", "generated"] {
                out.push(finding(
                    id,
                    Status::Skipped,
                    format!("{CONFIG} can't be read"),
                ));
            }
        }
        Ok((cfg, migrated)) => {
            if migrated.is_some() {
                out.push(
                    finding(
                        "config",
                        Status::Warning,
                        "it still has [[wire]] tables, which are [[link]] now",
                    )
                    .fix("`bonsai sync` renames them"),
                );
            } else {
                out.push(finding("config", Status::Ok, format!("{CONFIG} reads")));
            }
            check_graph(root, &cfg, &mut out);
            check_markers(root, Some(&cfg), &mut out);
        }
    }
    if !out.iter().any(|f| f.id == "markers") {
        check_markers(root, None, &mut out);
    }
    check_tools(root, &mut out);
    out
}

fn check_graph(root: &Path, cfg: &crate::graph::Config, out: &mut Vec<Finding>) {
    let report = crate::graph::check(cfg, &sync::read_messages(root));
    let sync_fix = format!("edit {CONFIG} (or use the bonsai commands), then `bonsai sync`");
    for e in &report.errors {
        out.push(finding("graph", Status::Error, e.clone()).fix(sync_fix.clone()));
    }
    for w in &report.warnings {
        out.push(finding("graph", Status::Warning, w.clone()));
    }
    if report.errors.is_empty() && report.warnings.is_empty() {
        let (b, e) = (cfg.branches.len(), cfg.edges.len());
        out.push(finding(
            "graph",
            Status::Ok,
            format!("{b} branch(es), {e} edge(s), {} link(s)", cfg.links.len()),
        ));
    }

    // Source files: missing ones, and ones bonsai.toml doesn't name (never
    // compiled: the module lists are generated from bonsai.toml).
    let mut sources = Vec::new();
    for b in &cfg.branches {
        let path = format!("src/branches/{}.rs", b.name);
        if !root.join(&path).is_file() {
            sources.push(
                finding(
                    "sources",
                    Status::Error,
                    format!("[branch.{}] has no {path}", b.name),
                )
                .about(path)
                .fix(format!(
                    "restore it, or remove the branch: `bonsai branch remove {}`",
                    b.name
                )),
            );
        }
    }
    for e in &cfg.edges {
        let path = format!("src/edges/{}.rs", e.name);
        if matches!(e.kind, crate::graph::EdgeKind::Custom { .. }) && !root.join(&path).is_file() {
            sources.push(
                finding(
                    "sources",
                    Status::Error,
                    format!("custom [edge.{}] has no {path}", e.name),
                )
                .about(path)
                .fix(format!(
                    "restore it, or remove the edge: `bonsai edge remove {}`",
                    e.name
                )),
            );
        }
    }
    let named = |dir: &str, name: &str| match dir {
        "branches" => cfg.branches.iter().any(|b| b.name == name),
        _ => {
            name == "serial"
                || cfg.edges.iter().any(|e| {
                    e.name == name && matches!(e.kind, crate::graph::EdgeKind::Custom { .. })
                })
        }
    };
    for dir in ["branches", "edges"] {
        let Ok(entries) = std::fs::read_dir(root.join("src").join(dir)) else {
            continue;
        };
        let mut names: Vec<String> = entries
            .flatten()
            .filter_map(|e| e.file_name().to_str().map(str::to_string))
            .filter_map(|f| f.strip_suffix(".rs").map(str::to_string))
            .filter(|n| n != "mod")
            .collect();
        names.sort();
        for name in names {
            if !named(dir, &name) {
                let path = format!("src/{dir}/{name}.rs");
                let (table, add) = match dir {
                    "branches" => (
                        format!("[branch.{name}]"),
                        format!("`bonsai branch add {name}` (keeps the file)"),
                    ),
                    _ => (
                        format!("a custom [edge.{name}]"),
                        format!("add `[edge.{name}]` with `kind = \"custom\"`, then `bonsai sync`"),
                    ),
                };
                sources.push(
                    finding(
                        "sources",
                        Status::Warning,
                        format!("{path} isn't compiled: {CONFIG} has no {table}"),
                    )
                    .about(path)
                    .fix(format!("delete it, or add it to the graph: {add}")),
                );
            }
        }
    }
    if sources.is_empty() {
        sources.push(finding(
            "sources",
            Status::Ok,
            "every branch and custom edge has its file",
        ));
    }
    out.extend(sources);

    // Generated files: what `bonsai sync` would change.
    if sync::interrupted(root) {
        out.push(
            finding(
                "generated",
                Status::Error,
                "a `bonsai sync` didn't finish: some files may be from before it, some after",
            )
            .about(sync::JOURNAL)
            .fix("`bonsai sync` finishes it"),
        );
    }
    match sync::plan(root) {
        Err(Refused::Errors(_)) => out.push(finding(
            "generated",
            Status::Skipped,
            "can't tell while the graph has errors (nothing would be generated)",
        )),
        Err(Refused::Config(e)) => out.push(finding(
            "generated",
            Status::Skipped,
            format!("can't work it out: {e}"),
        )),
        Ok(plan) if plan.changes.is_empty() => out.push(finding(
            "generated",
            Status::Ok,
            format!("generated code is in step with {CONFIG}"),
        )),
        Ok(plan) => {
            for change in &plan.changes {
                out.push(
                    finding(
                        "generated",
                        Status::Error,
                        format!(
                            "{} is out of date: `bonsai sync` would {} it",
                            change.path,
                            match change.kind() {
                                "created" => "create",
                                "removed" => "remove",
                                _ => "change",
                            }
                        ),
                    )
                    .about(change.path.clone())
                    .fix("`bonsai sync --dry-run` shows the change; `bonsai sync` makes it"),
                );
            }
        }
    }
}

/// The marker lines bonsai inserts at; in each branch `cfg` names (none
/// when the graph can't be read).
fn check_markers(root: &Path, cfg: Option<&crate::graph::Config>, out: &mut Vec<Finding>) {
    let whole_line = |src: &str, marker: &str| src.lines().any(|l| l.trim() == marker);
    match std::fs::read_to_string(root.join(MESSAGES)) {
        Ok(src) if whole_line(&src, MESSAGE_MARKER) => {}
        Ok(_) => out.push(
            finding(
                "markers",
                Status::Warning,
                format!("{MESSAGES} has no `{MESSAGE_MARKER}` line: `bonsai message add` can't add to it"),
            )
            .about(MESSAGES)
            .fix(format!("put a `{MESSAGE_MARKER}` line back, on its own, where new messages should go")),
        ),
        Err(e) => out.push(
            finding("markers", Status::Error, format!("can't read {MESSAGES}: {e}"))
                .about(MESSAGES)
                .fix("restore it: it holds the tree's messages"),
        ),
    }
    for branch in cfg.map(|c| c.branches.as_slice()).unwrap_or_default() {
        let rel = format!("src/branches/{}.rs", branch.name);
        if let Ok(src) = std::fs::read_to_string(root.join(&rel))
            && !whole_line(&src, INPUT_ARM)
        {
            out.push(
                finding(
                    "markers",
                    Status::Warning,
                    format!("{rel} has no `{INPUT_ARM}` line: link and rate won't add arms to it"),
                )
                .about(rel)
                .fix(format!(
                    "put `{INPUT_ARM}` back on its own line, last in `match input`"
                )),
            );
        }
    }
    if !out.iter().any(|f| f.id == "markers") {
        out.push(finding(
            "markers",
            Status::Ok,
            "the markers bonsai inserts at are in place",
        ));
    }
}

fn check_tools(root: &Path, out: &mut Vec<Finding>) {
    let on_path = tools::on_path;
    if on_path("cargo") {
        out.push(finding("toolchain.cargo", Status::Ok, "cargo is on PATH"));
    } else {
        out.push(
            finding("toolchain.cargo", Status::Error, "cargo isn't on PATH")
                .fix("install Rust with rustup (https://rustup.rs)"),
        );
    }
    let config = std::fs::read_to_string(root.join(".cargo/config.toml")).unwrap_or_default();
    let Some(target) = crate::parse_target(&config) else {
        out.push(finding(
            "toolchain.target",
            Status::Ok,
            "builds for this computer (no target set)",
        ));
        for t in tools::configured(&config) {
            check_tool(t, out);
        }
        return;
    };
    // The target's standard library.
    if !on_path("rustup") {
        out.push(
            finding(
                "toolchain.target",
                Status::Skipped,
                format!("rustup isn't on PATH, so whether {target} is installed can't be checked"),
            )
            .about(target.clone()),
        );
    } else {
        match std::process::Command::new("rustup")
            .args(["target", "list", "--installed"])
            .current_dir(root)
            .output()
        {
            Ok(o) if o.status.success() => {
                let installed = String::from_utf8_lossy(&o.stdout);
                if installed.lines().any(|l| l.trim() == target) {
                    out.push(
                        finding(
                            "toolchain.target",
                            Status::Ok,
                            format!("{target} is installed"),
                        )
                        .about(target.clone()),
                    );
                } else {
                    out.push(
                        finding(
                            "toolchain.target",
                            Status::Error,
                            format!("{target} isn't installed: the tree can't build for its board"),
                        )
                        .about(target.clone())
                        .fix(format!("rustup target add {target}")),
                    );
                }
            }
            _ => out.push(
                finding(
                    "toolchain.target",
                    Status::Skipped,
                    "`rustup target list --installed` failed",
                )
                .about(target.clone()),
            ),
        }
    }
    // The linker for the target.
    let section = format!("[target.{target}]");
    match crate::parse_scoped_key(&config, &section, "linker") {
        Some(linker) if linker.starts_with(".cargo/") => {
            if !root.join(&linker).is_file() {
                out.push(
                    finding("toolchain.linker", Status::Error, format!("the linker script {linker} is missing"))
                        .fix("`bonsai tools zigbuild` writes it again"),
                );
            } else {
                out.push(finding("toolchain.linker", Status::Ok, format!("links with {linker} (zig)")));
            }
        }
        Some(linker) if on_path(&linker) => {
            out.push(finding("toolchain.linker", Status::Ok, format!("{linker} is on PATH")))
        }
        Some(linker) => out.push(
            finding("toolchain.linker", Status::Error, format!("the linker {linker} isn't on PATH: builds for {target} won't link"))
                .fix("install it (Debian: `sudo apt install gcc-aarch64-linux-gnu`), or link with zig: `bonsai tools zigbuild`"),
        ),
        None => out.push(
            finding("toolchain.linker", Status::Error, format!("no linker set for {target}: builds for the board won't link"))
                .fix("link with zig: `bonsai tools zigbuild`"),
        ),
    }
    for t in tools::configured(&config) {
        check_tool(t, out);
    }
    // Where `cargo run` sends the program: reported, never contacted.
    match crate::parse_scoped_key(&config, "[env]", "BONSAI_PI") {
        Some(pi) => out.push(finding(
            "deploy.address",
            Status::Ok,
            format!("`cargo run` copies the program to {pi} over ssh (not contacted now)"),
        )),
        None => out.push(
            finding("deploy.address", Status::Warning, "no BONSAI_PI in .cargo/config.toml's [env]: `cargo run` doesn't know where the Pi is")
                .fix("add `BONSAI_PI = \"user@host\"` under [env] (or set it in the environment)"),
        ),
    }
}

fn check_tool(t: Tool, out: &mut Vec<Finding>) {
    let id = match t {
        Tool::Sccache => "tools.sccache",
        Tool::Mold => "tools.mold",
        Tool::Zigbuild => "tools.zigbuild",
        Tool::Bacon => "tools.bacon",
    };
    if t.installed() {
        out.push(finding(
            id,
            Status::Ok,
            format!("{} is set up and installed", t.name()),
        ));
    } else {
        out.push(
            finding(
                id,
                Status::Error,
                format!("the tree's build uses {}, but it isn't installed", t.name()),
            )
            .fix(format!("`bonsai tools {}` installs it", t.name())),
        );
    }
}

/// The worst status among `findings`.
pub fn worst(findings: &[Finding]) -> Status {
    findings
        .iter()
        .map(|f| f.status)
        .max()
        .unwrap_or(Status::Ok)
}

/// Exit code: 0 no errors (warnings and skipped checks allowed), 1 errors.
pub fn exit_code(findings: &[Finding]) -> i32 {
    i32::from(worst(findings) == Status::Error)
}

/// Readable, one line per finding, grouped by check.
pub fn render_text(findings: &[Finding]) -> String {
    let mut s = String::new();
    for f in findings {
        let mark = match f.status {
            Status::Ok => "  ok   ",
            Status::Skipped => "  skip ",
            Status::Warning => "  warn ",
            Status::Error => "  ERROR",
        };
        s += &format!("{mark} {:<17} {}\n", f.id, f.message);
        if let Some(fix) = &f.fix {
            s += &format!("{:26}→ {fix}\n", "");
        }
    }
    let count = |st| findings.iter().filter(|f| f.status == st).count();
    s += &format!(
        "\n{} error(s), {} warning(s), {} skipped\n",
        count(Status::Error),
        count(Status::Warning),
        count(Status::Skipped)
    );
    s
}

fn json_str(s: &str) -> String {
    let mut out = String::from("\"");
    for c in s.chars() {
        match c {
            '"' => out += "\\\"",
            '\\' => out += "\\\\",
            '\n' => out += "\\n",
            '\r' => out += "\\r",
            '\t' => out += "\\t",
            c if (c as u32) < 0x20 => out += &format!("\\u{:04x}", c as u32),
            c => out.push(c),
        }
    }
    out.push('"');
    out
}

/// One JSON object: `{"doctor":1,"status":…,"summary":{…},"checks":[…]}`.
pub fn render_json(findings: &[Finding]) -> String {
    let count = |st| findings.iter().filter(|f| f.status == st).count();
    let checks: Vec<String> = findings
        .iter()
        .map(|f| {
            let opt = |v: &Option<String>| v.as_deref().map_or("null".to_string(), json_str);
            format!(
                "{{\"id\":{},\"status\":{},\"subject\":{},\"message\":{},\"fix\":{}}}",
                json_str(f.id),
                json_str(f.status.name()),
                opt(&f.subject),
                json_str(&f.message),
                opt(&f.fix)
            )
        })
        .collect();
    format!(
        "{{\"doctor\":1,\"status\":{},\"summary\":{{\"ok\":{},\"warning\":{},\"error\":{},\"skipped\":{}}},\"checks\":[{}]}}\n",
        json_str(worst(findings).name()),
        count(Status::Ok),
        count(Status::Warning),
        count(Status::Error),
        count(Status::Skipped),
        checks.join(",")
    )
}

/// `bonsai doctor [--json]`.
pub fn doctor(args: &[String]) -> ! {
    let json = match args {
        [] => false,
        [a] if a == "--json" => true,
        _ => {
            eprintln!("usage: bonsai doctor [--json]");
            std::process::exit(2);
        }
    };
    let findings = check(Path::new("."));
    if json {
        print!("{}", render_json(&findings));
    } else {
        print!("{}", render_text(&findings));
    }
    std::process::exit(exit_code(&findings));
}

#[cfg(test)]
mod tests {
    use super::*;
    use std::path::PathBuf;

    /// A fresh host tree (the template as it ships) in its own folder.
    fn fixture(name: &str) -> PathBuf {
        let root =
            std::env::temp_dir().join(format!("bonsai-doctor-{}-{name}", std::process::id()));
        let _ = std::fs::remove_dir_all(&root);
        let tmpl = crate::TEMPLATES.get_dir("linux/host").unwrap();
        crate::extract_dir(tmpl, tmpl.path(), &root).unwrap();
        root
    }

    fn of<'a>(findings: &'a [Finding], id: &str) -> Vec<&'a Finding> {
        findings.iter().filter(|f| f.id == id).collect()
    }

    /// Every file under `root`, with its contents.
    fn snapshot(root: &Path) -> Vec<(PathBuf, Vec<u8>)> {
        fn walk(dir: &Path, out: &mut Vec<(PathBuf, Vec<u8>)>) {
            for e in std::fs::read_dir(dir).unwrap().flatten() {
                let p = e.path();
                if p.is_dir() {
                    walk(&p, out);
                } else {
                    out.push((p.clone(), std::fs::read(&p).unwrap()));
                }
            }
        }
        let mut out = Vec::new();
        walk(root, &mut out);
        out.sort();
        out
    }

    #[test]
    fn a_healthy_tree_passes() {
        let root = fixture("healthy");
        let findings = check(&root);
        assert_eq!(worst(&findings), Status::Ok, "{}", render_text(&findings));
        assert_eq!(exit_code(&findings), 0);
        for id in [
            "tree",
            "config",
            "graph",
            "sources",
            "generated",
            "markers",
            "toolchain.cargo",
        ] {
            assert_eq!(of(&findings, id).len(), 1, "{id}: {findings:?}");
        }
        let _ = std::fs::remove_dir_all(&root);
    }

    #[test]
    fn not_a_tree_says_so_and_checks_nothing_else() {
        let root = std::env::temp_dir().join(format!("bonsai-doctor-{}-empty", std::process::id()));
        std::fs::create_dir_all(&root).unwrap();
        let findings = check(&root);
        assert_eq!(findings.len(), 1);
        assert_eq!(
            (findings[0].id, findings[0].status),
            ("tree", Status::Error)
        );
        assert!(findings[0].fix.is_some());
        assert_eq!(exit_code(&findings), 1);
    }

    #[test]
    fn an_unreadable_config_skips_what_depends_on_it() {
        let root = fixture("bad-toml");
        std::fs::write(root.join(CONFIG), "[branch.sensor\n").unwrap();
        let findings = check(&root);
        let config = of(&findings, "config");
        assert_eq!(config[0].status, Status::Error, "{findings:?}");
        for id in ["graph", "sources", "generated"] {
            assert_eq!(of(&findings, id)[0].status, Status::Skipped, "{id}");
        }
        let _ = std::fs::remove_dir_all(&root);
    }

    #[test]
    fn graph_errors_and_missing_files_are_named() {
        let root = fixture("broken-graph");
        let toml = std::fs::read_to_string(root.join(CONFIG)).unwrap();
        std::fs::write(
            root.join(CONFIG),
            format!("{toml}\n[branch.sensor]\nrate = 1\n\n[[link]]\nfrom = \"sensor\"\nmessage = \"Nope\"\nto = [\"ghost\"]\n"),
        )
        .unwrap();
        let findings = check(&root);
        let graph = of(&findings, "graph");
        assert!(
            graph
                .iter()
                .any(|f| f.status == Status::Error && f.message.contains("ghost")),
            "{graph:?}"
        );
        let sources = of(&findings, "sources");
        assert!(
            sources.iter().any(|f| f.status == Status::Error
                && f.subject.as_deref() == Some("src/branches/sensor.rs")),
            "{sources:?}"
        );
        assert_eq!(of(&findings, "generated")[0].status, Status::Skipped);
        assert_eq!(exit_code(&findings), 1);
        let _ = std::fs::remove_dir_all(&root);
    }

    #[test]
    fn stale_generated_files_are_found_and_left_alone() {
        let root = fixture("stale");
        let toml = std::fs::read_to_string(root.join(CONFIG)).unwrap();
        // A branch added by hand: its table and file, but no sync.
        std::fs::write(
            root.join(CONFIG),
            format!("{toml}\n[branch.sensor]\nlimit = 3\n"),
        )
        .unwrap();
        let scaffold = crate::tree::BRANCH_TEMPLATE
            .replace("{{branch_name}}", "sensor")
            .replace("{{BranchName}}", "Sensor");
        std::fs::write(root.join("src/branches/sensor.rs"), scaffold).unwrap();
        let before = snapshot(&root);
        let findings = check(&root);
        let stale: Vec<&str> = of(&findings, "generated")
            .iter()
            .filter(|f| f.status == Status::Error)
            .filter_map(|f| f.subject.as_deref())
            .collect();
        assert_eq!(
            stale,
            ["src/links.rs", "src/settings.rs", "src/branches/mod.rs"]
        );
        assert_eq!(snapshot(&root), before, "doctor changed the tree");
        let _ = std::fs::remove_dir_all(&root);
    }

    #[test]
    fn files_outside_the_graph_and_lost_markers_are_warnings() {
        let root = fixture("strays");
        std::fs::write(root.join("src/branches/extra.rs"), "").unwrap();
        let messages = std::fs::read_to_string(root.join(MESSAGES)).unwrap();
        std::fs::write(root.join(MESSAGES), messages.replace(MESSAGE_MARKER, "")).unwrap();
        let findings = check(&root);
        let warned: Vec<(&str, Option<&str>)> = findings
            .iter()
            .filter(|f| f.status == Status::Warning)
            .map(|f| (f.id, f.subject.as_deref()))
            .collect();
        assert_eq!(
            warned,
            [
                ("sources", Some("src/branches/extra.rs")),
                ("markers", Some(MESSAGES))
            ]
        );
        assert_eq!(exit_code(&findings), 0, "warnings alone don't fail");
        let _ = std::fs::remove_dir_all(&root);
    }

    #[test]
    fn a_build_tool_that_isnt_installed_is_an_error() {
        let root = fixture("tools");
        std::fs::write(
            root.join(".cargo/config.toml"),
            "[build]\nrustc-wrapper = \"sccache\"\n",
        )
        .unwrap();
        let findings = check(&root);
        let sccache = of(&findings, "tools.sccache");
        assert_eq!(sccache.len(), 1);
        let want = if Tool::Sccache.installed() {
            Status::Ok
        } else {
            Status::Error
        };
        assert_eq!(sccache[0].status, want);
        let _ = std::fs::remove_dir_all(&root);
    }

    #[test]
    fn json_is_one_object_with_stable_ids_and_escaped_text() {
        let findings = vec![
            finding("graph", Status::Error, "a \"quoted\"\nline").fix("do\tthis"),
            finding("tree", Status::Ok, "fine").about("x"),
        ];
        assert_eq!(
            render_json(&findings),
            "{\"doctor\":1,\"status\":\"error\",\"summary\":{\"ok\":1,\"warning\":0,\"error\":1,\"skipped\":0},\"checks\":[\
             {\"id\":\"graph\",\"status\":\"error\",\"subject\":null,\"message\":\"a \\\"quoted\\\"\\nline\",\"fix\":\"do\\tthis\"},\
             {\"id\":\"tree\",\"status\":\"ok\",\"subject\":\"x\",\"message\":\"fine\",\"fix\":null}]}\n"
        );
    }
}
