//! The commands that grow a tree: branches, messages, wires and rates, and
//! `sync`, which regenerates the code they imply. The graph lives in
//! `bonsai.toml` (edited with toml_edit, so comments stay); the message types
//! in `src/messages.rs`; each branch's handling in `src/branches/<name>.rs`.

use std::io;
use std::path::{Path, PathBuf};
use std::str::FromStr;

use toml_edit::{Array, ArrayOfTables, DocumentMut, Item, Table, value};

use crate::graph::{self, Config};

pub const CONFIG: &str = "bonsai.toml";
pub const MESSAGES: &str = "src/messages.rs";
const RUNTIME_RS: &str = "src/bonsai.rs";
const WIRING_RS: &str = "src/wiring.rs";
const SETTINGS_RS: &str = "src/settings.rs";
const BRANCHES_MOD: &str = "src/branches/mod.rs";

/// Where `bonsai wire` adds a receiving arm, and `bonsai message add` a type.
pub const INPUT_ARM: &str = "// bonsai:input-arm";
pub const MESSAGE_MARKER: &str = "// bonsai:message";

/// The runtime every tree carries as `src/bonsai.rs`, kept current by `sync`.
pub const RUNTIME: &str = include_str!("../templates/_tree/bonsai.rs");
/// The branch scaffold. `{{branch_name}}` and `{{BranchName}}` are plain
/// replacements, not Liquid.
pub const BRANCH_TEMPLATE: &str = include_str!("../templates/_branch/branch.rs");

/// Names a message can't take: the generated code's own.
const RESERVED: &[&str] = &[
    "Tick", "Msg", "Input", "Out", "Core", "Slot", "Event", "Tree", "Sends", "Branch", "VecDeque",
];

fn exit(msg: impl std::fmt::Display) -> ! {
    eprintln!("{msg}");
    std::process::exit(1);
}

fn usage(msg: impl std::fmt::Display) -> ! {
    eprintln!("{msg}");
    std::process::exit(2);
}

/// Refuse anything but a bonsai tree of this version.
pub fn require_tree(cmd: &str) {
    let cargo = std::fs::read_to_string("Cargo.toml").unwrap_or_default();
    if Path::new("src/sap.rs").exists() || cargo.contains("embassy-executor") {
        exit(format!(
            "this tree was grown by an older bonsai (Embassy, src/sap.rs), which `{cmd}` no\n\
             longer works on. Plant a new tree (`bonsai`) and move your code into its branches."
        ));
    }
    if !cargo.contains("Generated by bonsai for") || !Path::new(CONFIG).is_file() {
        exit(format!(
            "run `bonsai {cmd}` inside a bonsai tree (no bonsai.toml and Cargo.toml stamp here)"
        ));
    }
}

fn read(path: &str) -> String {
    std::fs::read_to_string(path).unwrap_or_else(|e| exit(format!("can't read {path}: {e}")))
}

fn load_doc() -> DocumentMut {
    DocumentMut::from_str(&read(CONFIG)).unwrap_or_else(|e| exit(format!("{CONFIG}: {e}")))
}

fn load() -> Config {
    graph::parse(&read(CONFIG)).unwrap_or_else(|e| exit(e))
}

fn messages() -> Vec<String> {
    graph::parse_messages(&std::fs::read_to_string(MESSAGES).unwrap_or_default())
}

fn branch_file(name: &str) -> PathBuf {
    Path::new("src/branches").join(format!("{name}.rs"))
}

/// Write `content` to `path` if it differs. True when it changed.
fn write_if_changed(path: &str, content: &str) -> io::Result<bool> {
    if std::fs::read_to_string(path).is_ok_and(|old| old == content) {
        return Ok(false);
    }
    if let Some(dir) = Path::new(path).parent() {
        std::fs::create_dir_all(dir)?;
    }
    std::fs::write(path, content)?;
    Ok(true)
}

/// Regenerate everything the graph implies. Refuses (exit 1) when the graph
/// has errors, leaving the generated files as they were.
pub fn sync_tree() -> io::Result<()> {
    let cfg = load();
    let report = graph::check(&cfg, &messages());
    for b in &cfg.branches {
        if !branch_file(&b.name).is_file() {
            eprintln!(
                "error: [branch.{}] has no src/branches/{}.rs (`bonsai branch add {}` makes one)",
                b.name, b.name, b.name
            );
            std::process::exit(1);
        }
    }
    if !report.errors.is_empty() {
        for e in &report.errors {
            eprintln!("error: {e}");
        }
        exit("bonsai.toml has errors; nothing was generated");
    }
    let mut changed = Vec::new();
    for (path, content) in [
        (RUNTIME_RS, RUNTIME.to_string()),
        (WIRING_RS, graph::render_wiring(&cfg)),
        (SETTINGS_RS, graph::render_settings(&cfg)),
        (BRANCHES_MOD, graph::render_mod(&cfg)),
    ] {
        if write_if_changed(path, &content)? {
            changed.push(path);
        }
    }
    if changed.is_empty() {
        println!("generated code is in step with {CONFIG}");
    } else {
        println!("updated {}", changed.join(", "));
    }
    for w in &report.warnings {
        println!("warning: {w}");
    }
    Ok(())
}

/// `bonsai sync`.
pub fn sync() -> io::Result<()> {
    require_tree("sync");
    sync_tree()
}

// ---------------------------------------------------------------------------
// Editing bonsai.toml
// ---------------------------------------------------------------------------

fn save_doc(doc: &DocumentMut) -> io::Result<()> {
    std::fs::write(CONFIG, doc.to_string())
}

/// The `[branch]` super-table, created implicit so only `[branch.x]` headers show.
fn branch_tables(doc: &mut DocumentMut) -> &mut Table {
    let item = doc.entry("branch").or_insert_with(|| {
        let mut t = Table::new();
        t.set_implicit(true);
        Item::Table(t)
    });
    item.as_table_mut()
        .unwrap_or_else(|| exit(format!("{CONFIG}: `branch` must be tables")))
}

fn wires(doc: &mut DocumentMut) -> &mut ArrayOfTables {
    doc.entry("wire")
        .or_insert_with(|| Item::ArrayOfTables(ArrayOfTables::new()))
        .as_array_of_tables_mut()
        .unwrap_or_else(|| exit(format!("{CONFIG}: wires must be [[wire]] tables")))
}

fn str_of<'a>(t: &'a Table, key: &str) -> &'a str {
    t.get(key).and_then(Item::as_str).unwrap_or_default()
}

fn to_list(t: &Table) -> Vec<String> {
    t.get("to")
        .and_then(Item::as_array)
        .map(|a| {
            a.iter()
                .filter_map(|v| v.as_str().map(str::to_string))
                .collect()
        })
        .unwrap_or_default()
}

fn set_to_list(t: &mut Table, to: &[String]) {
    t.insert("to", value(Array::from_iter(to.iter().map(String::as_str))));
}

// ---------------------------------------------------------------------------
// Editing branch files: the arms of `match input`
// ---------------------------------------------------------------------------

/// `RouteFollow` → `route_follow`, for an arm's binding.
fn snake(camel: &str) -> String {
    let mut out = String::new();
    for (i, c) in camel.chars().enumerate() {
        if c.is_ascii_uppercase() {
            if i > 0 {
                out.push('_');
            }
            out.push(c.to_ascii_lowercase());
        } else {
            out.push(c);
        }
    }
    out
}

/// The arm `wire` adds for a message (or `rate` for its tick).
fn arm(message: Option<&str>) -> String {
    match message {
        Some(m) => format!("Input::{m}(_{}) => {{}}", snake(m)),
        None => "Input::Tick => {}".to_string(),
    }
}

/// Whether a line opens the arm for `message` (None: the tick).
fn is_input_arm(line: &str, message: Option<&str>) -> bool {
    let rest = line.trim_start().strip_prefix("Input::");
    match message {
        Some(m) => rest
            .and_then(|r| r.strip_prefix(m))
            .is_some_and(|r| r.starts_with('(')),
        None => rest
            .and_then(|r| r.strip_prefix("Tick"))
            .is_some_and(|r| r.starts_with([' ', '=', '|'])),
    }
}

/// Add the arm to `branch`'s `match input`, unless it has one already.
fn add_arm(branch: &str, message: Option<&str>) -> io::Result<()> {
    let path = branch_file(branch);
    let src = std::fs::read_to_string(&path)?;
    if src.lines().any(|l| is_input_arm(l, message)) {
        return Ok(());
    }
    match crate::insert_indented_before(&src, INPUT_ARM, &arm(message)) {
        Some(new) => std::fs::write(&path, new),
        None => {
            eprintln!(
                "note: no `{INPUT_ARM}` line in {}: add `{}` to its match yourself",
                path.display(),
                arm(message)
            );
            Ok(())
        }
    }
}

/// Take the arm out of `branch`'s `match input`, body and all.
fn remove_arm(branch: &str, message: Option<&str>) -> io::Result<()> {
    let path = branch_file(branch);
    let Ok(src) = std::fs::read_to_string(&path) else {
        return Ok(());
    };
    if let Some(new) = crate::remove_balanced_span(&src, |l| is_input_arm(l, message)) {
        std::fs::write(&path, new)?;
    }
    Ok(())
}

/// Whether any wire in `doc` still delivers `message` to `branch`.
fn receives(doc: &DocumentMut, branch: &str, message: &str) -> bool {
    doc.get("wire")
        .and_then(Item::as_array_of_tables)
        .is_some_and(|ws| {
            ws.iter()
                .any(|w| str_of(w, "message") == message && to_list(w).iter().any(|t| t == branch))
        })
}

// ---------------------------------------------------------------------------
// Commands
// ---------------------------------------------------------------------------

/// `bonsai branch add <name>`.
pub fn branch_add(name: &str) -> io::Result<()> {
    require_tree("branch add");
    if !graph::is_branch_name(name) {
        usage(format!(
            "`{name}`: a branch name is snake_case (a-z, 0-9, _) and not a Rust keyword"
        ));
    }
    let cfg = load();
    let path = branch_file(name);
    if cfg.branches.iter().any(|b| b.name == name) || path.exists() {
        exit(format!("there's already a branch `{name}`"));
    }
    let src = BRANCH_TEMPLATE
        .replace("{{branch_name}}", name)
        .replace("{{BranchName}}", &graph::camel(name));
    std::fs::create_dir_all("src/branches")?;
    std::fs::write(&path, src)?;
    let mut doc = load_doc();
    branch_tables(&mut doc).insert(name, Item::Table(Table::new()));
    save_doc(&doc)?;
    println!("added branch {name}: {}", path.display());
    sync_tree()
}

/// `bonsai branch remove <name>`: its file, its table, and every wire from or
/// to it (with the arms those wires put in other branches).
pub fn branch_remove(name: &str) -> io::Result<()> {
    require_tree("branch remove");
    let mut doc = load_doc();
    let known = doc
        .get("branch")
        .and_then(Item::as_table_like)
        .is_some_and(|t| t.contains_key(name));
    if !known {
        exit(format!("no branch `{name}` in {CONFIG}"));
    }
    if let Some(t) = doc.get_mut("branch").and_then(Item::as_table_like_mut) {
        t.remove(name);
    }
    // Wires from it go; it leaves every `to` list.
    let mut lost: Vec<(String, String)> = Vec::new(); // (receiver, message)
    if let Some(ws) = doc.get_mut("wire").and_then(Item::as_array_of_tables_mut) {
        let mut i = 0;
        while i < ws.len() {
            let w = ws.get_mut(i).expect("index in range");
            let message = str_of(w, "message").to_string();
            let mut to = to_list(w);
            if str_of(w, "from") == name {
                lost.extend(to.iter().map(|t| (t.clone(), message.clone())));
                ws.remove(i);
                continue;
            }
            if to.iter().any(|t| t == name) {
                to.retain(|t| t != name);
                if to.is_empty() {
                    ws.remove(i);
                    continue;
                }
                set_to_list(w, &to);
            }
            i += 1;
        }
    }
    save_doc(&doc)?;
    for (receiver, message) in lost {
        if receiver != name && !receives(&doc, &receiver, &message) {
            remove_arm(&receiver, Some(&message))?;
        }
    }
    let path = branch_file(name);
    if path.exists() {
        std::fs::remove_file(&path)?;
    }
    println!("removed branch {name}");
    sync_tree()
}

fn is_message_name(name: &str) -> bool {
    crate::is_ident(name) && name.chars().next().is_some_and(|c| c.is_ascii_uppercase())
}

/// The struct `message add` writes for `name` with `fields` (`name:type`).
fn message_struct(name: &str, fields: &[(String, String)]) -> String {
    let mut s = "#[derive(Clone, Debug)]\n".to_string();
    if fields.is_empty() {
        s.push_str(&format!("pub struct {name};\n"));
    } else {
        s.push_str(&format!("pub struct {name} {{\n"));
        for (f, t) in fields {
            s.push_str(&format!("    pub {f}: {t},\n"));
        }
        s.push_str("}\n");
    }
    s
}

/// `bonsai message add <Name> [field:type …]`.
pub fn message_add(name: &str, fields: &[String]) -> io::Result<()> {
    require_tree("message add");
    if !is_message_name(name) {
        usage(format!(
            "`{name}`: a message name is an UpperCamelCase identifier"
        ));
    }
    if RESERVED.contains(&name) {
        usage(format!(
            "`{name}` is a name the generated code uses; pick another"
        ));
    }
    if messages().iter().any(|m| m == name) {
        exit(format!("there's already a message `{name}` in {MESSAGES}"));
    }
    let fields = crate::parse_fields(fields);
    let src = read(MESSAGES);
    let new = crate::insert_before_marker(
        Path::new(MESSAGES),
        src,
        MESSAGE_MARKER,
        &(message_struct(name, &fields) + "\n"),
    );
    std::fs::write(MESSAGES, new)?;
    println!("added message {name} to {MESSAGES}");
    Ok(())
}

/// Take `name`'s struct out of `src`, with the attributes and doc comments
/// right above it and one blank line after. None if it isn't there.
fn without_struct(src: &str, name: &str) -> Option<String> {
    let lines: Vec<&str> = src.split_inclusive('\n').collect();
    let is_it = |l: &str| {
        l.strip_prefix("pub struct ")
            .and_then(|r| r.strip_prefix(name))
            .is_some_and(|r| r.starts_with([';', ' ', '{', '(', '<']))
    };
    let at = lines.iter().position(|l| is_it(l))?;
    let mut start = at;
    while start > 0 {
        let above = lines[start - 1].trim_start();
        if above.starts_with("#[") || above.starts_with("///") {
            start -= 1;
        } else {
            break;
        }
    }
    // Through the line where every bracket the struct opened has closed.
    let mut end = at;
    let mut depth = crate::bracket_depth(lines[at]);
    while depth > 0 && end + 1 < lines.len() {
        end += 1;
        depth += crate::bracket_depth(lines[end]);
    }
    end += 1;
    if lines.get(end).is_some_and(|l| l.trim().is_empty()) {
        end += 1;
    }
    Some(lines[..start].concat() + &lines[end..].concat())
}

/// `bonsai message remove <Name>`: refused while a wire carries it.
pub fn message_remove(name: &str) -> io::Result<()> {
    require_tree("message remove");
    let cfg = load();
    let users: Vec<String> = cfg
        .wires
        .iter()
        .filter(|w| w.message == name)
        .map(|w| format!("{} --{}--> {}", w.from, w.message, w.to.join(", ")))
        .collect();
    if !users.is_empty() {
        exit(format!(
            "{name} is still wired; unwire it first:\n  {}",
            users.join("\n  ")
        ));
    }
    let src = read(MESSAGES);
    let Some(new) = without_struct(&src, name) else {
        exit(format!("no `pub struct {name}` in {MESSAGES}"));
    };
    std::fs::write(MESSAGES, new)?;
    println!("removed message {name} from {MESSAGES}");
    Ok(())
}

/// `bonsai wire <from> <Message> <to …>`: `from` sends it to each of `to`.
pub fn wire(from: &str, message: &str, to: &[String]) -> io::Result<()> {
    require_tree("wire");
    let cfg = load();
    let is_branch = |n: &str| cfg.branches.iter().any(|b| b.name == n);
    if !is_branch(from) {
        exit(format!("no branch `{from}`"));
    }
    if !messages().iter().any(|m| m == message) {
        exit(format!(
            "no message `{message}` in {MESSAGES} (`bonsai message add {message}` makes one)"
        ));
    }
    for t in to {
        if !is_branch(t) {
            exit(format!("no branch `{t}`"));
        }
        if t == from {
            exit(format!(
                "a branch can't send to itself; keep that in {from}'s own state"
            ));
        }
    }
    let mut doc = load_doc();
    let ws = wires(&mut doc);
    let existing = ws
        .iter_mut()
        .find(|w| str_of(w, "from") == from && str_of(w, "message") == message);
    let added: Vec<String> = match existing {
        Some(w) => {
            let mut list = to_list(w);
            let new: Vec<String> = to.iter().filter(|t| !list.contains(t)).cloned().collect();
            list.extend(new.iter().cloned());
            set_to_list(w, &list);
            new
        }
        None => {
            let mut t = Table::new();
            t.insert("from", value(from));
            t.insert("message", value(message));
            set_to_list(&mut t, to);
            ws.push(t);
            to.to_vec()
        }
    };
    if added.is_empty() {
        println!("{from} already sends {message} to {}", to.join(", "));
        return Ok(());
    }
    save_doc(&doc)?;
    for t in &added {
        add_arm(t, Some(message))?;
    }
    println!(
        "{from} --{message}--> {}: send it from {from} with `out.send({message} {{ .. }})`",
        added.join(", ")
    );
    sync_tree()
}

/// `bonsai unwire <from> <Message> [<to …>]`: all receivers when none named.
pub fn unwire(from: &str, message: &str, to: &[String]) -> io::Result<()> {
    require_tree("unwire");
    let mut doc = load_doc();
    let ws = wires(&mut doc);
    let Some(i) = ws
        .iter()
        .position(|w| str_of(w, "from") == from && str_of(w, "message") == message)
    else {
        exit(format!("{from} isn't wired to send {message}"));
    };
    let w = ws.get_mut(i).expect("found above");
    let mut list = to_list(w);
    let dropped: Vec<String> = if to.is_empty() {
        std::mem::take(&mut list)
    } else {
        for t in to {
            if !list.contains(t) {
                exit(format!("{from} doesn't send {message} to {t}"));
            }
        }
        list.retain(|t| !to.contains(t));
        to.to_vec()
    };
    if list.is_empty() {
        ws.remove(i);
    } else {
        set_to_list(w, &list);
    }
    save_doc(&doc)?;
    for t in &dropped {
        if !receives(&doc, t, message) {
            remove_arm(t, Some(message))?;
        }
    }
    let still = !list.is_empty();
    println!(
        "{from} no longer sends {message} to {}{}",
        dropped.join(", "),
        if still {
            String::new()
        } else {
            format!("; take its `out.send({message} ..)` out of {from}")
        }
    );
    sync_tree()
}

/// `bonsai rate <branch> <hz|off>`: tick the branch this many times a second.
pub fn rate(branch: &str, hz: &str) -> io::Result<()> {
    require_tree("rate");
    let mut doc = load_doc();
    let tables = branch_tables(&mut doc);
    let Some(t) = tables.get_mut(branch).and_then(Item::as_table_mut) else {
        exit(format!("no branch `{branch}` in {CONFIG}"));
    };
    if hz == "off" {
        if t.remove("rate").is_none() {
            println!("{branch} has no rate");
            return Ok(());
        }
        save_doc(&doc)?;
        remove_arm(branch, None)?;
        println!("{branch} no longer ticks");
    } else {
        let Some(n) = hz.parse::<f64>().ok().filter(|n| *n > 0.0 && n.is_finite()) else {
            usage(format!(
                "rate is ticks per second (like 10 or 0.5), or `off`; got {hz:?}"
            ));
        };
        if n.fract() == 0.0 && n < i64::MAX as f64 {
            t.insert("rate", value(n as i64));
        } else {
            t.insert("rate", value(n));
        }
        save_doc(&doc)?;
        add_arm(branch, None)?;
        println!("{branch} ticks {hz} times a second: `Input::Tick` in its process");
    }
    sync_tree()
}

/// `bonsai list`: the tree's branches and wires.
pub fn list() -> io::Result<()> {
    require_tree("list");
    let cargo = std::fs::read_to_string("Cargo.toml").unwrap_or_default();
    let name = crate::parse_package_name(&cargo).unwrap_or_else(|| "?".to_string());
    let board = crate::parse_board(&cargo)
        .and_then(|b| crate::chip_of(&b).map(|chip| format!("{b} ({chip})")))
        .unwrap_or_else(|| "unknown board".to_string());
    let cfg = load();
    println!("tree: {name}  ({board})");
    println!("branches, in the order the core runs them:");
    for b in &cfg.branches {
        let mut about = Vec::new();
        if let Some(hz) = b.rate {
            about.push(format!("ticks {hz}/s"));
        }
        if !b.settings.is_empty() {
            let keys: Vec<&str> = b.settings.iter().map(|(k, _)| k.as_str()).collect();
            about.push(format!("settings: {}", keys.join(", ")));
        }
        println!(
            "  {}{}",
            b.name,
            if about.is_empty() {
                String::new()
            } else {
                format!("  ({})", about.join("; "))
            }
        );
    }
    if cfg.wires.is_empty() {
        println!("wires: none yet (`bonsai wire <from> <Message> <to>`)");
    } else {
        println!("wires:");
        for w in &cfg.wires {
            println!("  {} --{}--> {}", w.from, w.message, w.to.join(", "));
        }
    }
    let report = graph::check(&cfg, &messages());
    for e in &report.errors {
        println!("error: {e}");
    }
    for w in &report.warnings {
        println!("warning: {w}");
    }
    Ok(())
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn arms_match_their_message_only() {
        assert!(is_input_arm(
            "            Input::Beat(_beat) => {}",
            Some("Beat")
        ));
        assert!(is_input_arm("Input::Beat(b) => {", Some("Beat")));
        assert!(!is_input_arm("Input::BeatTwice(b) => {}", Some("Beat")));
        assert!(is_input_arm("    Input::Tick => {}", None));
        assert!(is_input_arm("Input::Tick | Input::Beat(_) => {}", None));
        assert!(!is_input_arm("Input::TickTock(_) => {}", None));
        assert_eq!(
            arm(Some("RouteFollow")),
            "Input::RouteFollow(_route_follow) => {}"
        );
        assert_eq!(arm(None), "Input::Tick => {}");
    }

    #[test]
    fn message_structs_round_trip() {
        let base = "//! doc\n\n// bonsai:message\n";
        let with = crate::insert_before_marker(
            Path::new(MESSAGES),
            base.to_string(),
            MESSAGE_MARKER,
            &(message_struct("Reading", &[("temp".into(), "f32".into())]) + "\n"),
        );
        assert_eq!(
            with,
            "//! doc\n\n#[derive(Clone, Debug)]\npub struct Reading {\n    pub temp: f32,\n}\n\n// bonsai:message\n"
        );
        let with_two = crate::insert_before_marker(
            Path::new(MESSAGES),
            with.clone(),
            MESSAGE_MARKER,
            &(message_struct("Beat", &[]) + "\n"),
        );
        assert_eq!(graph::parse_messages(&with_two), ["Reading", "Beat"]);
        assert_eq!(without_struct(&with_two, "Beat").unwrap(), with);
        assert_eq!(without_struct(&with, "Reading").unwrap(), base);
        assert!(without_struct(&with, "Read").is_none());
    }
}
