//! The commands that grow a tree: branches, edges, messages, links and rates,
//! and `sync`, which regenerates the code they imply. The graph lives in
//! `bonsai.toml` (edited with toml_edit, so comments stay); the message types
//! in `src/messages.rs`; each branch's handling in `src/branches/<name>.rs`;
//! each custom edge in `src/edges/<name>.rs`.

use std::io;
use std::path::{Path, PathBuf};
use std::str::FromStr;

use toml_edit::{Array, ArrayOfTables, DocumentMut, Item, Table, value};

use crate::graph::{self, Config};

pub const CONFIG: &str = "bonsai.toml";
pub const MESSAGES: &str = "src/messages.rs";
const RUNTIME_RS: &str = "src/bonsai.rs";
const LINKS_RS: &str = "src/links.rs";
const OLD_WIRING_RS: &str = "src/wiring.rs";
const SETTINGS_RS: &str = "src/settings.rs";
const BRANCHES_MOD: &str = "src/branches/mod.rs";
const EDGES_MOD: &str = "src/edges/mod.rs";
const SERIAL_RS: &str = "src/edges/serial.rs";

/// Where `bonsai link` adds a receiving arm, and `bonsai message add` a type.
pub const INPUT_ARM: &str = "// bonsai:input-arm";
pub const MESSAGE_MARKER: &str = "// bonsai:message";

/// The runtime every tree carries as `src/bonsai.rs`, kept current by `sync`.
pub const RUNTIME: &str = include_str!("../templates/_tree/bonsai.rs");
/// The serial edge, written to `src/edges/serial.rs` while a tree has one.
pub const SERIAL: &str = include_str!("../templates/_tree/serial.rs");
/// The crate the serial edge needs, added and removed with it.
const TOKIO_SERIAL: (&str, &str) = ("tokio-serial", "5.5");
/// The runtime reads the local time with it (for run logs).
const LIBC: (&str, &str) = ("libc", "0.2");
/// The scaffolds. `{{branch_name}}`/`{{BranchName}}` and
/// `{{edge_name}}`/`{{EdgeName}}` are plain replacements, not Liquid.
pub const BRANCH_TEMPLATE: &str = include_str!("../templates/_branch/branch.rs");
pub const EDGE_TEMPLATE: &str = include_str!("../templates/_edge/edge.rs");

/// Names a message can't take: the generated code's own.
const RESERVED: &[&str] = &[
    "Tick", "Msg", "Input", "Out", "Core", "Slot", "Event", "Tree", "Sends", "Branch", "VecDeque",
    "EdgeIn", "EdgeOut", "Edge", "Packet",
];

/// The types in the runtime's `units` module (`src/bonsai.rs`): usable as
/// message fields, and not as message names.
pub const UNITS: &[&str] = &[
    "Celsius",
    "Fahrenheit",
    "Kelvin",
    "Meters",
    "Feet",
    "Kilometers",
    "MetersPerSecond",
    "Knots",
    "KilometersPerHour",
    "Seconds",
    "Hertz",
    "Degrees",
    "Radians",
    "Volts",
    "Amps",
    "Watts",
    "Pascals",
    "Hectopascals",
    "Percent",
];

const UNITS_IMPORT: &str = "pub use crate::bonsai::units::*;";

fn exit(msg: impl std::fmt::Display) -> ! {
    eprintln!("{msg}");
    std::process::exit(1);
}

fn usage(msg: impl std::fmt::Display) -> ! {
    eprintln!("{msg}");
    std::process::exit(2);
}

/// Refuse anything but a bonsai tree of this version.
pub fn require_tree(cmd: &str) {
    let cargo = std::fs::read_to_string("Cargo.toml").unwrap_or_default();
    if Path::new("src/sap.rs").exists() || cargo.contains("embassy-executor") {
        exit(format!(
            "this tree was grown by an older bonsai (Embassy, src/sap.rs), which `{cmd}` no\n\
             longer works on. Plant a new tree (`bonsai`) and move your code into its branches."
        ));
    }
    if !cargo.contains("Generated by bonsai for") || !Path::new(CONFIG).is_file() {
        exit(format!(
            "run `bonsai {cmd}` inside a bonsai tree (no bonsai.toml and Cargo.toml stamp here)"
        ));
    }
    if let Some(src) = with_links(&read(CONFIG)) {
        std::fs::write(CONFIG, src).unwrap_or_else(|e| exit(format!("can't write {CONFIG}: {e}")));
        println!("{CONFIG}: [[wire]] tables are [[link]] now");
    }
}

/// Every `.rs` file under `dir`, recursively.
fn rust_files(dir: &Path) -> io::Result<Vec<PathBuf>> {
    let mut out = Vec::new();
    for entry in std::fs::read_dir(dir)? {
        let path = entry?.path();
        if path.is_dir() {
            out.extend(rust_files(&path)?);
        } else if path.extension().is_some_and(|e| e == "rs") {
            out.push(path);
        }
    }
    Ok(out)
}

/// Source from a tree whose generated module was `wiring`, using `links`
/// instead (`mod links;`, `crate::links::…`, `links::Core`); None when it
/// never names it.
pub fn with_links_module(src: &str) -> Option<String> {
    let mut out = String::with_capacity(src.len());
    let mut rest = src;
    while let Some(at) = rest.find("wiring") {
        let before = rest[..at].chars().next_back();
        let after = &rest[at + "wiring".len()..];
        let word = !before.is_some_and(|c| c.is_alphanumeric() || c == '_');
        let declared = rest[..at].ends_with("mod ") && after.starts_with(';');
        let module = word && (after.starts_with("::") || declared);
        out.push_str(&rest[..at]);
        out.push_str(if module { "links" } else { "wiring" });
        rest = after;
    }
    out.push_str(rest);
    (out != src).then_some(out)
}

/// A `bonsai.toml` from before wires were called links, with each `[[wire]]`
/// header renamed; None when it has none.
pub fn with_links(src: &str) -> Option<String> {
    let old = |l: &str| l.trim() == "[[wire]]";
    if !src.lines().any(old) {
        return None;
    }
    Some(
        src.split_inclusive('\n')
            .map(|l| {
                if old(l) {
                    l.replacen("[[wire]]", "[[link]]", 1)
                } else {
                    l.to_string()
                }
            })
            .collect(),
    )
}

fn read(path: &str) -> String {
    std::fs::read_to_string(path).unwrap_or_else(|e| exit(format!("can't read {path}: {e}")))
}

fn load_doc() -> DocumentMut {
    DocumentMut::from_str(&read(CONFIG)).unwrap_or_else(|e| exit(format!("{CONFIG}: {e}")))
}

fn load() -> Config {
    graph::parse(&read(CONFIG)).unwrap_or_else(|e| exit(e))
}

fn messages() -> Vec<String> {
    graph::parse_messages(&std::fs::read_to_string(MESSAGES).unwrap_or_default())
}

fn branch_file(name: &str) -> PathBuf {
    Path::new("src/branches").join(format!("{name}.rs"))
}

fn edge_file(name: &str) -> PathBuf {
    Path::new("src/edges").join(format!("{name}.rs"))
}

/// Write `content` to `path` if it differs. True when it changed.
fn write_if_changed(path: &str, content: &str) -> io::Result<bool> {
    if std::fs::read_to_string(path).is_ok_and(|old| old == content) {
        return Ok(false);
    }
    if let Some(dir) = Path::new(path).parent() {
        std::fs::create_dir_all(dir)?;
    }
    std::fs::write(path, content)?;
    Ok(true)
}

/// Regenerate everything the graph implies. Refuses (exit 1) when the graph
/// has errors, leaving the generated files as they were.
pub fn sync_tree() -> io::Result<()> {
    let cfg = load();
    let report = graph::check(&cfg, &messages());
    let mut missing = Vec::new();
    for b in &cfg.branches {
        if !branch_file(&b.name).is_file() {
            missing.push(format!(
                "[branch.{0}] has no src/branches/{0}.rs (`bonsai branch add {0}` makes one)",
                b.name
            ));
        }
    }
    for e in &cfg.edges {
        if matches!(e.kind, graph::EdgeKind::Custom { .. }) && !edge_file(&e.name).is_file() {
            missing.push(format!(
                "[edge.{0}] is custom but has no src/edges/{0}.rs (`bonsai edge add {0} --custom` makes one)",
                e.name
            ));
        }
    }
    if !report.errors.is_empty() || !missing.is_empty() {
        for e in report.errors.iter().chain(&missing) {
            eprintln!("error: {e}");
        }
        exit("the tree has errors; nothing was generated");
    }
    let mut changed = Vec::new();
    // Trees from before src/wiring.rs was src/links.rs: move their code across.
    if Path::new(OLD_WIRING_RS).exists() {
        let mut moved = 0;
        for path in rust_files(Path::new("src"))? {
            if let Some(new) = with_links_module(&std::fs::read_to_string(&path)?) {
                std::fs::write(&path, new)?;
                moved += 1;
            }
        }
        std::fs::remove_file(OLD_WIRING_RS)?;
        changed.push(format!(
            "{OLD_WIRING_RS} → {LINKS_RS} ({moved} files now use crate::links)"
        ));
    }
    for (path, content) in [
        (RUNTIME_RS, RUNTIME.to_string()),
        (LINKS_RS, graph::render_links(&cfg)),
        (SETTINGS_RS, graph::render_settings(&cfg)),
        (BRANCHES_MOD, graph::render_mod(&cfg)),
        (EDGES_MOD, graph::render_edges_mod(&cfg)),
    ] {
        if write_if_changed(path, &content)? {
            changed.push(path.to_string());
        }
    }
    // Trees from before the log macros: bring them into scope.
    if let Some(new) = with_macro_use(&read("src/main.rs")) {
        std::fs::write("src/main.rs", new)?;
        changed.push("src/main.rs (#[macro_use] mod bonsai)".to_string());
    }
    // The serial edge's code and crate come and go with the tree's serial edges.
    let manifest = read("Cargo.toml");
    if cfg.has_serial() {
        if write_if_changed(SERIAL_RS, SERIAL)? {
            changed.push(SERIAL_RS.to_string());
        }
        if let Some(new) = crate::with_dependency(&manifest, TOKIO_SERIAL)? {
            std::fs::write("Cargo.toml", new)?;
            changed.push(format!("Cargo.toml (+{})", TOKIO_SERIAL.0));
        }
    } else {
        if Path::new(SERIAL_RS).exists() {
            std::fs::remove_file(SERIAL_RS)?;
            changed.push(format!("{SERIAL_RS} (removed)"));
        }
        if let Some(new) = crate::without_dependency(&manifest, TOKIO_SERIAL.0)? {
            std::fs::write("Cargo.toml", new)?;
            changed.push(format!("Cargo.toml (-{})", TOKIO_SERIAL.0));
        }
    }
    // Trees from before run logs: the runtime needs libc now.
    if let Some(new) = crate::with_dependency(&read("Cargo.toml"), LIBC)? {
        std::fs::write("Cargo.toml", new)?;
        changed.push(format!("Cargo.toml (+{})", LIBC.0));
    }
    if changed.is_empty() {
        println!("generated code is in step with {CONFIG}");
    } else {
        println!("updated {}", changed.join(", "));
    }
    for w in &report.warnings {
        println!("warning: {w}");
    }
    Ok(())
}

/// `bonsai sync`.
pub fn sync() -> io::Result<()> {
    require_tree("sync");
    sync_tree()
}

// ---------------------------------------------------------------------------
// Editing bonsai.toml
// ---------------------------------------------------------------------------

fn save_doc(doc: &DocumentMut) -> io::Result<()> {
    std::fs::write(CONFIG, header_first(doc))
}

fn has_comment(text: &str) -> bool {
    text.lines().any(|l| l.trim_start().starts_with('#'))
}

/// `doc` as text, with its comments above its tables when every table is new:
/// in a bonsai.toml with no tables yet, toml_edit keeps all the comments
/// after them.
fn header_first(doc: &DocumentMut) -> String {
    let text = doc.to_string();
    let trailing = doc.trailing().as_str().unwrap_or_default();
    let Some(body) = text.strip_suffix(trailing) else {
        return text;
    };
    if body.trim().is_empty() || !has_comment(trailing) || has_comment(body) {
        return text;
    }
    format!("{}\n\n{}", trailing.trim_end(), body.trim_start())
}

/// Where each table of `doc` is, in file order: (key, sub-key or index).
fn table_paths(doc: &DocumentMut) -> Vec<(String, Option<String>, Option<usize>)> {
    let mut found = Vec::new();
    for (key, item) in doc.iter() {
        match item {
            Item::Table(t) if t.is_implicit() => {
                for (sub, item) in t.iter() {
                    if let Item::Table(t) = item {
                        found.push((t.position(), key.to_string(), Some(sub.to_string()), None));
                    }
                }
            }
            Item::Table(t) => found.push((t.position(), key.to_string(), None, None)),
            Item::ArrayOfTables(ts) => {
                for (i, t) in ts.iter().enumerate() {
                    found.push((t.position(), key.to_string(), None, Some(i)));
                }
            }
            _ => {}
        }
    }
    // Tables not yet placed (new ones) come after the rest.
    found.sort_by_key(|(pos, ..)| pos.unwrap_or(isize::MAX));
    found
        .into_iter()
        .map(|(_, k, sub, i)| (k, sub, i))
        .collect()
}

/// Keep the comments that were above a removed table: above whatever table
/// now comes first, or at the end when none is left.
fn keep_comments(doc: &mut DocumentMut, prefix: &str) {
    if !has_comment(prefix) {
        return;
    }
    let first = table_paths(doc).into_iter().next();
    let table = match first {
        Some((key, Some(sub), _)) => doc[&key][&sub].as_table_mut(),
        Some((key, None, Some(i))) => doc[&key]
            .as_array_of_tables_mut()
            .and_then(|ts| ts.get_mut(i)),
        Some((key, None, None)) => doc[&key].as_table_mut(),
        None => None,
    };
    match table {
        Some(t) => {
            let old = t
                .decor()
                .prefix()
                .and_then(|p| p.as_str())
                .unwrap_or_default();
            let new = format!("{prefix}{old}");
            t.decor_mut().set_prefix(new);
        }
        None => {
            let old = doc.trailing().as_str().unwrap_or_default();
            let new = format!("{}\n{old}", prefix.trim_end());
            doc.set_trailing(new);
        }
    }
}

/// The comments above a table, when it has any.
fn prefix_of(item: &Item) -> String {
    let t = match item {
        Item::Table(t) => t,
        _ => return String::new(),
    };
    t.decor()
        .prefix()
        .and_then(|p| p.as_str())
        .unwrap_or_default()
        .to_string()
}

/// The `[<kind>]` super-table (`branch`, `edge`), created implicit so only
/// `[kind.x]` headers show.
fn tables<'a>(doc: &'a mut DocumentMut, kind: &str) -> &'a mut Table {
    let item = doc.entry(kind).or_insert_with(|| {
        let mut t = Table::new();
        t.set_implicit(true);
        Item::Table(t)
    });
    item.as_table_mut()
        .unwrap_or_else(|| exit(format!("{CONFIG}: `{kind}` must be tables")))
}

fn links(doc: &mut DocumentMut) -> &mut ArrayOfTables {
    doc.entry("link")
        .or_insert_with(|| Item::ArrayOfTables(ArrayOfTables::new()))
        .as_array_of_tables_mut()
        .unwrap_or_else(|| exit(format!("{CONFIG}: links must be [[link]] tables")))
}

fn str_of<'a>(t: &'a Table, key: &str) -> &'a str {
    t.get(key).and_then(Item::as_str).unwrap_or_default()
}

fn message_of(t: &Table) -> Option<&str> {
    t.get("message").and_then(Item::as_str)
}

fn to_list(t: &Table) -> Vec<String> {
    t.get("to")
        .and_then(Item::as_array)
        .map(|a| {
            a.iter()
                .filter_map(|v| v.as_str().map(str::to_string))
                .collect()
        })
        .unwrap_or_default()
}

fn set_to_list(t: &mut Table, to: &[String]) {
    t.insert("to", value(Array::from_iter(to.iter().map(String::as_str))));
}

/// Save `doc` if it's a valid graph; exit, leaving the file alone, if not.
fn save_checked(doc: &DocumentMut) -> io::Result<Config> {
    let cfg = graph::parse(&doc.to_string()).unwrap_or_else(|e| exit(e));
    save_doc(doc)?;
    Ok(cfg)
}

// ---------------------------------------------------------------------------
// Editing branch files: the arms of `match input`
// ---------------------------------------------------------------------------

/// `RouteFollow` → `route_follow`, for an arm's binding.
fn snake(camel: &str) -> String {
    let mut out = String::new();
    for (i, c) in camel.chars().enumerate() {
        if c.is_ascii_uppercase() {
            if i > 0 {
                out.push('_');
            }
            out.push(c.to_ascii_lowercase());
        } else {
            out.push(c);
        }
    }
    out
}

/// The arm for an input variant: a message, an edge (CamelCase) or `Tick`.
fn arm(variant: &str) -> String {
    match variant {
        "Tick" => "Input::Tick => {}".to_string(),
        v => format!("Input::{v}(_{}) => {{}}", snake(v)),
    }
}

/// Whether a line opens the arm for `variant`.
fn is_input_arm(line: &str, variant: &str) -> bool {
    line.trim_start()
        .strip_prefix("Input::")
        .and_then(|r| r.strip_prefix(variant))
        .is_some_and(|r| {
            if variant == "Tick" {
                r.starts_with([' ', '=', '|'])
            } else {
                r.starts_with('(')
            }
        })
}

/// Add the arm to `branch`'s `match input`, unless it has one already.
fn add_arm(branch: &str, variant: &str) -> io::Result<()> {
    let path = branch_file(branch);
    let Ok(src) = std::fs::read_to_string(&path) else {
        return Ok(());
    };
    let src = crate::marker_on_own_line(&src, INPUT_ARM);
    if src.lines().any(|l| is_input_arm(l, variant)) {
        return Ok(());
    }
    match crate::insert_indented_before(&src, INPUT_ARM, &arm(variant)) {
        Some(new) => std::fs::write(&path, new),
        None => {
            eprintln!(
                "note: no `{INPUT_ARM}` line in {}: add `{}` to its match yourself",
                path.display(),
                arm(variant)
            );
            Ok(())
        }
    }
}

/// Take the arm out of `branch`'s `match input`, body and all.
fn remove_arm(branch: &str, variant: &str) -> io::Result<()> {
    let path = branch_file(branch);
    let Ok(src) = std::fs::read_to_string(&path) else {
        return Ok(());
    };
    // Put a pulled-up marker back first, so it isn't removed with its arm.
    let fixed = crate::marker_on_own_line(&src, INPUT_ARM);
    if let Some(new) = crate::remove_balanced_span(&fixed, |l| is_input_arm(l, variant)) {
        std::fs::write(&path, new)?;
    }
    Ok(())
}

/// Bring every branch's arms in step with a graph change: add an arm for each
/// input it gained, remove the arm of each it lost.
fn reconcile_arms(before: &Config, after: &Config) -> io::Result<()> {
    for b in &after.branches {
        let old = graph::input_variants(before, &b.name);
        let new = graph::input_variants(after, &b.name);
        for v in old.iter().filter(|v| !new.contains(v)) {
            remove_arm(&b.name, v)?;
        }
        for v in new.iter().filter(|v| !old.contains(v)) {
            add_arm(&b.name, v)?;
        }
    }
    Ok(())
}

// ---------------------------------------------------------------------------
// Commands
// ---------------------------------------------------------------------------

fn check_new_name(cfg: &Config, name: &str, what: &str) {
    if !graph::is_branch_name(name) || graph::RESERVED_NAMES.contains(&name) {
        usage(format!(
            "`{name}`: a {what} name is snake_case (a-z, 0-9, _), not a Rust keyword, and not `serial`"
        ));
    }
    if cfg.is_branch(name) || cfg.edge(name).is_some() {
        exit(format!("there's already a branch or edge `{name}`"));
    }
}

/// `bonsai branch add <name>`.
pub fn branch_add(name: &str) -> io::Result<()> {
    require_tree("branch add");
    let cfg = load();
    check_new_name(&cfg, name, "branch");
    let path = branch_file(name);
    if path.exists() {
        exit(format!("{} already exists", path.display()));
    }
    let src = BRANCH_TEMPLATE
        .replace("{{branch_name}}", name)
        .replace("{{BranchName}}", &graph::camel(name));
    std::fs::create_dir_all("src/branches")?;
    std::fs::write(&path, src)?;
    let mut doc = load_doc();
    tables(&mut doc, "branch").insert(name, Item::Table(Table::new()));
    save_doc(&doc)?;
    println!("added branch {name}: {}", path.display());
    sync_tree()
}

/// Remove a branch's or edge's table and every link from it, and take it
/// out of every `to` list; returns the new graph.
fn remove_node(doc: &mut DocumentMut, kind: &str, name: &str) -> io::Result<Config> {
    let mut comments = String::new();
    if let Some(t) = doc.get_mut(kind).and_then(Item::as_table_like_mut)
        && let Some(item) = t.remove(name)
    {
        comments += &prefix_of(&item);
    }
    if let Some(ws) = doc.get_mut("link").and_then(Item::as_array_of_tables_mut) {
        let mut i = 0;
        while i < ws.len() {
            let w = ws.get_mut(i).expect("index in range");
            let mut to = to_list(w);
            let gone = if str_of(w, "from") == name {
                true
            } else if to.iter().any(|t| t == name) {
                to.retain(|t| t != name);
                if !to.is_empty() {
                    set_to_list(w, &to);
                }
                to.is_empty()
            } else {
                false
            };
            if gone {
                let w = ws.get(i).expect("index in range");
                comments += w
                    .decor()
                    .prefix()
                    .and_then(|p| p.as_str())
                    .unwrap_or_default();
                ws.remove(i);
            } else {
                i += 1;
            }
        }
    }
    keep_comments(doc, &comments);
    save_checked(doc)
}

/// `bonsai branch remove <name>`: its file, its table, and every link from or
/// to it (with the arms those links put in other branches).
pub fn branch_remove(name: &str) -> io::Result<()> {
    require_tree("branch remove");
    let before = load();
    if !before.is_branch(name) {
        exit(format!("no branch `{name}` in {CONFIG}"));
    }
    let mut doc = load_doc();
    let after = remove_node(&mut doc, "branch", name)?;
    reconcile_arms(&before, &after)?;
    let path = branch_file(name);
    if path.exists() {
        std::fs::remove_file(&path)?;
    }
    println!("removed branch {name}");
    sync_tree()
}

/// `bonsai edge add <name> <kind> [--key value …]`, or `--custom`.
pub fn edge_add(name: &str, args: &[String]) -> io::Result<()> {
    require_tree("edge add");
    let cfg = load();
    check_new_name(&cfg, name, "edge");
    let (kind, rest) = match args.split_first() {
        Some((flag, rest)) if flag == "--custom" => ("custom", rest),
        Some((kind, rest)) if !kind.starts_with('-') => (kind.as_str(), rest),
        _ => usage("usage: bonsai edge add <name> udp|tcp|serial [--key value …], or --custom"),
    };
    let table = edge_table(kind, rest).unwrap_or_else(|e| usage(e));
    let mut doc = load_doc();
    tables(&mut doc, "edge").insert(name, Item::Table(table));
    save_checked(&doc)?;
    if kind == "custom" {
        let path = edge_file(name);
        if !path.exists() {
            let src = EDGE_TEMPLATE
                .replace("{{edge_name}}", name)
                .replace("{{EdgeName}}", &graph::camel(name));
            std::fs::create_dir_all("src/edges")?;
            std::fs::write(&path, src)?;
        }
        println!("added edge {name}: {}", path.display());
    } else {
        println!("added {kind} edge {name}");
    }
    println!(
        "link it one way or both: `bonsai link {name} <branch>` (what it receives), `bonsai link <branch> {name}` (what it sends)"
    );
    sync_tree()
}

/// An edge's `bonsai.toml` table from `edge add`'s `--key value` flags.
fn edge_table(kind: &str, rest: &[String]) -> Result<Table, String> {
    let mut table = Table::new();
    table.insert("kind", value(kind));
    let mut i = 0;
    while i < rest.len() {
        let Some(key) = rest[i].strip_prefix("--") else {
            return Err(format!(
                "expected --key, got {:?} (flags go --key value, e.g. --bind 0.0.0.0:6969)",
                rest[i]
            ));
        };
        let key = key.replace('-', "_");
        if key == "reply" {
            table.insert("reply", value(true));
            i += 1;
            continue;
        }
        let v = match rest.get(i + 1) {
            Some(v) if !v.starts_with("--") => v,
            got => {
                let got = got.map_or("nothing".to_string(), |g| g.to_string());
                return Err(format!("--{key} takes {}, got {got}", wants(&key)));
            }
        };
        if key == "join" {
            let mut groups = table
                .get("join")
                .and_then(Item::as_array)
                .cloned()
                .unwrap_or_default();
            groups.push(v.as_str());
            table.insert("join", value(groups));
        } else {
            match v.parse::<i64>() {
                Ok(n) if key == "baud" => table.insert(&key, value(n)),
                _ => table.insert(&key, value(v.as_str())),
            };
        }
        i += 2;
    }
    Ok(table)
}

/// What an `edge add` flag takes, for its error.
fn wants(key: &str) -> &'static str {
    match key {
        "bind" | "to" | "connect" | "listen" => "an address (like 0.0.0.0:6969)",
        "join" => "a group address (like 239.2.3.1)",
        "iface" => "an interface address (like 192.168.1.10)",
        "device" => "a path (like /dev/serial0)",
        "baud" => "a number (like 9600)",
        "framing" => "raw or lines",
        _ => "a value",
    }
}

/// `bonsai edge remove <name>`: its table, its links and the arms they fed,
/// and a custom edge's file.
pub fn edge_remove(name: &str) -> io::Result<()> {
    require_tree("edge remove");
    let before = load();
    let Some(edge) = before.edge(name) else {
        exit(format!("no edge `{name}` in {CONFIG}"));
    };
    let custom = matches!(edge.kind, graph::EdgeKind::Custom { .. });
    let mut doc = load_doc();
    let after = remove_node(&mut doc, "edge", name)?;
    reconcile_arms(&before, &after)?;
    let path = edge_file(name);
    if custom && path.exists() {
        std::fs::remove_file(&path)?;
    }
    println!("removed edge {name}");
    sync_tree()
}

fn is_message_name(name: &str) -> bool {
    crate::is_ident(name) && name.chars().next().is_some_and(|c| c.is_ascii_uppercase())
}

/// The struct `message add` writes for `name` with `fields` (`name:type`).
fn message_struct(name: &str, fields: &[(String, String)]) -> String {
    let mut s = "#[derive(Clone, Debug)]\n".to_string();
    if fields.is_empty() {
        s.push_str(&format!("pub struct {name};\n"));
    } else {
        s.push_str(&format!("pub struct {name} {{\n"));
        for (f, t) in fields {
            s.push_str(&format!("    pub {f}: {t},\n"));
        }
        s.push_str("}\n");
    }
    s
}

/// `bonsai message add <Name> [field:type …]`.
pub fn message_add(name: &str, fields: &[String]) -> io::Result<()> {
    require_tree("message add");
    if !is_message_name(name) {
        usage(format!(
            "`{name}`: a message name is an UpperCamelCase identifier"
        ));
    }
    if RESERVED.contains(&name) || UNITS.contains(&name) {
        usage(format!(
            "`{name}` is a name the generated code uses; pick another"
        ));
    }
    if messages().iter().any(|m| m == name) {
        exit(format!("there's already a message `{name}` in {MESSAGES}"));
    }
    let fields = crate::parse_fields(fields);
    let mut src = read(MESSAGES);
    if fields.iter().any(|(_, ty)| uses_units(ty))
        && let Some(with) = with_units_import(&src)
    {
        src = with;
    }
    let new = crate::insert_before_marker(
        Path::new(MESSAGES),
        src,
        MESSAGE_MARKER,
        &(message_struct(name, &fields) + "\n"),
    );
    std::fs::write(MESSAGES, new)?;
    println!("added message {name} to {MESSAGES}");
    Ok(())
}

/// Whether a field type names a unit (`Celsius`, `Vec<Meters>`, `Option<Knots>`).
fn uses_units(ty: &str) -> bool {
    ty.split(|c: char| !c.is_alphanumeric() && c != '_')
        .any(|word| UNITS.contains(&word))
}

/// `src` (src/messages.rs) with the units in scope, below its doc comment;
/// None when they already are. Trees planted before units lack the line.
fn with_units_import(src: &str) -> Option<String> {
    if src.lines().any(|l| l.trim() == UNITS_IMPORT) {
        return None;
    }
    let docs: usize = src
        .split_inclusive('\n')
        .take_while(|l| l.starts_with("//!"))
        .map(str::len)
        .sum();
    let (head, rest) = src.split_at(docs);
    let blank = if head.is_empty() { "" } else { "\n" };
    Some(format!(
        "{head}{blank}#[allow(unused_imports)] // units (`temp: Celsius`), here and in every branch\n{UNITS_IMPORT}\n{}",
        if rest.starts_with('\n') {
            rest.to_string()
        } else {
            format!("\n{rest}")
        }
    ))
}

/// Take `name`'s struct out of `src`, with the attributes and doc comments
/// right above it and one blank line after. None if it isn't there.
fn without_struct(src: &str, name: &str) -> Option<String> {
    let lines: Vec<&str> = src.split_inclusive('\n').collect();
    let is_it = |l: &str| {
        l.strip_prefix("pub struct ")
            .and_then(|r| r.strip_prefix(name))
            .is_some_and(|r| r.starts_with([';', ' ', '{', '(', '<']))
    };
    let at = lines.iter().position(|l| is_it(l))?;
    let mut start = at;
    while start > 0 {
        let above = lines[start - 1].trim_start();
        if above.starts_with("#[") || above.starts_with("///") {
            start -= 1;
        } else {
            break;
        }
    }
    // Through the line where every bracket the struct opened has closed.
    let mut end = at;
    let mut depth = crate::bracket_depth(lines[at]);
    while depth > 0 && end + 1 < lines.len() {
        end += 1;
        depth += crate::bracket_depth(lines[end]);
    }
    end += 1;
    if lines.get(end).is_some_and(|l| l.trim().is_empty()) {
        end += 1;
    }
    Some(lines[..start].concat() + &lines[end..].concat())
}

/// `bonsai message remove <Name>`: refused while a link carries it.
pub fn message_remove(name: &str) -> io::Result<()> {
    require_tree("message remove");
    let cfg = load();
    let users: Vec<String> = cfg
        .links
        .iter()
        .filter(|w| w.message.as_deref() == Some(name))
        .map(graph::describe)
        .collect();
    if !users.is_empty() {
        exit(format!(
            "{name} is still linked; unlink it first:\n  {}",
            users.join("\n  ")
        ));
    }
    let src = read(MESSAGES);
    let Some(new) = without_struct(&src, name) else {
        exit(format!("no `pub struct {name}` in {MESSAGES}"));
    };
    std::fs::write(MESSAGES, new)?;
    println!("removed message {name} from {MESSAGES}");
    Ok(())
}

/// `bonsai link` takes `<from> <Message> <to…>` between branches, or
/// `<from> <to…>` when an edge is at one end. Message names are UpperCamel
/// and branch and edge names snake_case, so the two can't be confused.
fn split_link_args(args: &[String]) -> (Option<&str>, &[String]) {
    match args.split_first() {
        Some((m, rest)) if is_message_name(m) => (Some(m.as_str()), rest),
        _ => (None, args),
    }
}

/// `bonsai link <from> [<Message>] <to …>`.
pub fn link(from: &str, args: &[String]) -> io::Result<()> {
    require_tree("link");
    let (message, to) = split_link_args(args);
    if to.is_empty() {
        usage(
            "usage: bonsai link <from> <Message> <to> [<to> …], or bonsai link <from> <to> … with an edge",
        );
    }
    let before = load();
    if !before.is_branch(from) && before.edge(from).is_none() {
        exit(format!("no branch or edge `{from}`"));
    }
    if let Some(m) = message
        && !messages().iter().any(|x| x == m)
    {
        exit(format!(
            "no message `{m}` in {MESSAGES} (`bonsai message add {m}` makes one)"
        ));
    }
    let mut doc = load_doc();
    let ws = links(&mut doc);
    let existing = ws
        .iter_mut()
        .find(|w| str_of(w, "from") == from && message_of(w) == message);
    let added: Vec<String> = match existing {
        Some(w) => {
            let mut list = to_list(w);
            let new: Vec<String> = to.iter().filter(|t| !list.contains(t)).cloned().collect();
            list.extend(new.iter().cloned());
            set_to_list(w, &list);
            new
        }
        None => {
            let mut t = Table::new();
            t.insert("from", value(from));
            if let Some(m) = message {
                t.insert("message", value(m));
            }
            set_to_list(&mut t, to);
            ws.push(t);
            to.to_vec()
        }
    };
    if added.is_empty() {
        println!("that's linked already");
        return Ok(());
    }
    let after = graph::parse(&doc.to_string()).unwrap_or_else(|e| exit(e));
    let report = graph::check(&after, &messages());
    if !report.errors.is_empty() {
        for e in &report.errors {
            eprintln!("error: {e}");
        }
        exit("not linked");
    }
    save_doc(&doc)?;
    reconcile_arms(&before, &after)?;
    match message {
        Some(m) => println!(
            "{from} --{m}--> {}: send it from {from} with `out.send({m} {{ .. }})`",
            added.join(", ")
        ),
        None if before.edge(from).is_some() => println!(
            "{from} --> {}: what {from} receives arrives as `Input::{}(..)`",
            added.join(", "),
            graph::camel(from)
        ),
        None => println!(
            "{from} --> {}: send from {from} with {}",
            added.join(", "),
            added
                .iter()
                .map(|e| format!("`out.to_{e}(..)`"))
                .collect::<Vec<_>>()
                .join(", ")
        ),
    }
    sync_tree()
}

/// `bonsai unlink <from> [<Message>] [<to …>]`: all receivers when none named.
pub fn unlink(from: &str, args: &[String]) -> io::Result<()> {
    require_tree("unlink");
    let (message, to) = split_link_args(args);
    let before = load();
    let mut doc = load_doc();
    let ws = links(&mut doc);
    let Some(i) = ws
        .iter()
        .position(|w| str_of(w, "from") == from && message_of(w) == message)
    else {
        exit(match message {
            Some(m) => format!("{from} isn't linked to send {m}"),
            None => format!("{from} has no link without a message"),
        });
    };
    let w = ws.get_mut(i).expect("found above");
    let mut list = to_list(w);
    let dropped: Vec<String> = if to.is_empty() {
        std::mem::take(&mut list)
    } else {
        for t in to {
            if !list.contains(t) {
                exit(format!("{from} isn't linked to {t}"));
            }
        }
        list.retain(|t| !to.contains(t));
        to.to_vec()
    };
    let mut comments = String::new();
    if list.is_empty() {
        comments += w
            .decor()
            .prefix()
            .and_then(|p| p.as_str())
            .unwrap_or_default();
        ws.remove(i);
    } else {
        set_to_list(w, &list);
    }
    keep_comments(&mut doc, &comments);
    let after = save_checked(&doc)?;
    reconcile_arms(&before, &after)?;
    let sender_note = match message {
        Some(m) if list.is_empty() => format!("; take its `out.send({m} ..)` out of {from}"),
        None if before.is_branch(from) => format!(
            "; take its {} out of {from}",
            dropped
                .iter()
                .map(|e| format!("`out.to_{e}(..)`"))
                .collect::<Vec<_>>()
                .join(", ")
        ),
        _ => String::new(),
    };
    println!("unlinked {from} from {}{sender_note}", dropped.join(", "));
    sync_tree()
}

/// `bonsai rate <branch> <hz|off>`: tick the branch this many times a second.
pub fn rate(branch: &str, hz: &str) -> io::Result<()> {
    require_tree("rate");
    let before = load();
    let mut doc = load_doc();
    let Some(t) = tables(&mut doc, "branch")
        .get_mut(branch)
        .and_then(Item::as_table_mut)
    else {
        exit(format!("no branch `{branch}` in {CONFIG}"));
    };
    if hz == "off" {
        if t.remove("rate").is_none() {
            println!("{branch} has no rate");
            return Ok(());
        }
        println!("{branch} no longer ticks");
    } else {
        let Some(n) = hz.parse::<f64>().ok().filter(|n| *n > 0.0 && n.is_finite()) else {
            usage(format!(
                "rate is ticks per second (like 10 or 0.5), or `off`; got {hz:?}"
            ));
        };
        if n.fract() == 0.0 && n < i64::MAX as f64 {
            t.insert("rate", value(n as i64));
        } else {
            t.insert("rate", value(n));
        }
        let how_often = if n == 1.0 {
            "once a second".to_string()
        } else {
            format!("{hz} times a second")
        };
        println!("{branch} ticks {how_often}: `Input::Tick` in its process");
    }
    let after = save_checked(&doc)?;
    reconcile_arms(&before, &after)?;
    sync_tree()
}

/// `bonsai list`: the tree's branches, edges and links.
pub fn list() -> io::Result<()> {
    require_tree("list");
    let cargo = std::fs::read_to_string("Cargo.toml").unwrap_or_default();
    let name = crate::parse_package_name(&cargo).unwrap_or_else(|| "?".to_string());
    let board = crate::parse_board(&cargo)
        .and_then(|b| crate::chip_of(&b).map(|chip| format!("{b} ({chip})")))
        .unwrap_or_else(|| "unknown board".to_string());
    let cfg = load();
    println!("tree: {name}  ({board})");
    if cfg.branches.is_empty() {
        println!("branches: none yet (`bonsai branch add <name>`)");
    } else {
        println!("branches, in the order the core runs them:");
    }
    for b in &cfg.branches {
        let mut about = Vec::new();
        if let Some(hz) = b.rate {
            about.push(format!("ticks {hz}/s"));
        }
        if !b.settings.is_empty() {
            let keys: Vec<&str> = b.settings.iter().map(|(k, _)| k.as_str()).collect();
            about.push(format!("settings: {}", keys.join(", ")));
        }
        println!(
            "  {}{}",
            b.name,
            if about.is_empty() {
                String::new()
            } else {
                format!("  ({})", about.join("; "))
            }
        );
    }
    if !cfg.edges.is_empty() {
        println!("edges:");
        for e in &cfg.edges {
            println!("  {}  ({})", e.name, e.kind.summary());
        }
    }
    if cfg.links.is_empty() {
        println!("links: none yet (`bonsai link <from> <Message> <to>`)");
    } else {
        println!("links:");
        for w in &cfg.links {
            println!("  {}", graph::describe(w));
        }
    }
    println!("{}", record_summary(&cfg));
    let report = graph::check(&cfg, &messages());
    for e in &report.errors {
        println!("error: {e}");
    }
    for w in &report.warnings {
        println!("warning: {w}");
    }
    Ok(())
}

/// `record: events, panics → logs/`, for `bonsai list` and `bonsai record`.
pub fn record_summary(cfg: &Config) -> String {
    match &cfg.record {
        Some(r) if !r.kept().is_empty() => {
            format!(
                "record: {} → {}/",
                r.kept().join(", "),
                r.dir.trim_end_matches('/')
            )
        }
        _ => "record: nothing (`bonsai record events on`)".to_string(),
    }
}

/// Set `key` in `t`, keeping the comment after its old value in its column.
fn set_keeping_comment(t: &mut Table, key: &str, new: toml_edit::Value) {
    let mut new = new;
    if let Some(old) = t.get(key).and_then(Item::as_value) {
        let decor = old.decor();
        let prefix = decor.prefix().and_then(|p| p.as_str()).unwrap_or(" ");
        let suffix = decor.suffix().and_then(|s| s.as_str()).unwrap_or("");
        let pad = suffix.len() - suffix.trim_start_matches(' ').len();
        let bare = |v: &toml_edit::Value| v.clone().decorated("", "").to_string().len();
        let (old_len, new_len) = (bare(old), bare(&new));
        let suffix = match suffix.trim_start_matches(' ') {
            comment if comment.starts_with('#') => {
                let pad = (pad + old_len).saturating_sub(new_len).max(1);
                format!("{}{comment}", " ".repeat(pad))
            }
            _ => suffix.to_string(),
        };
        new.decor_mut().set_prefix(prefix);
        new.decor_mut().set_suffix(suffix);
    }
    t.insert(key, Item::Value(new));
}

/// `bonsai record [<kind> on|off | dir <folder>]`: which run logs to keep.
pub fn record(args: &[String]) -> io::Result<()> {
    require_tree("record");
    let mut doc = load_doc();
    if !doc.contains_key("record") {
        if args.is_empty() {
            println!("{}", record_summary(&load()));
            return Ok(());
        }
        let mut t = Table::new();
        t.decor_mut().set_prefix(
            "\n# Run logs: a folder per run in `dir`, a file for each kind set true.\n",
        );
        t.insert("dir", value("logs"));
        for kind in graph::RECORD_KINDS {
            t.insert(kind, value(false));
        }
        doc.insert("record", Item::Table(t));
    }
    let Some(t) = doc.get_mut("record").and_then(Item::as_table_mut) else {
        exit(format!("{CONFIG}: `record` is a table: [record]"));
    };
    match args {
        [] => {}
        [dir, folder] if dir == "dir" => set_keeping_comment(t, "dir", folder.as_str().into()),
        [kind, on] if graph::RECORD_KINDS.contains(&kind.as_str()) => {
            let on = match on.as_str() {
                "on" | "true" => true,
                "off" | "false" => false,
                _ => usage(format!(
                    "`bonsai record {kind}` takes on or off; got {on:?}"
                )),
            };
            set_keeping_comment(t, kind, on.into());
        }
        _ => usage(format!(
            "usage: bonsai record [{} on|off], or bonsai record dir <folder>",
            graph::RECORD_KINDS.join("|")
        )),
    }
    let cfg = save_checked(&doc)?;
    println!("{}", record_summary(&cfg));
    if args.is_empty() {
        return Ok(());
    }
    sync_tree()
}

/// `main_src` with `#[macro_use]` above `mod bonsai;` (so every module can
/// log with `info!` and friends), or None when it's there already or there's
/// no `mod bonsai;` line.
pub fn with_macro_use(main_src: &str) -> Option<String> {
    let lines: Vec<&str> = main_src.lines().collect();
    let at = lines.iter().position(|l| l.trim() == "mod bonsai;")?;
    if at > 0 && lines[at - 1].trim() == "#[macro_use]" {
        return None;
    }
    let indent = &lines[at][..lines[at].len() - lines[at].trim_start().len()];
    let mut out = String::with_capacity(main_src.len() + 16);
    for (i, line) in main_src.split_inclusive('\n').enumerate() {
        if i == at {
            out.push_str(indent);
            out.push_str("#[macro_use]\n");
        }
        out.push_str(line);
    }
    Some(out)
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn the_wiring_module_becomes_links() {
        let main = "#[rustfmt::skip]\nmod wiring;\n\nfn main() {\n    bonsai::run(wiring::Core::new());\n}\n";
        assert_eq!(
            with_links_module(main).as_deref(),
            Some(
                "#[rustfmt::skip]\nmod links;\n\nfn main() {\n    bonsai::run(links::Core::new());\n}\n"
            )
        );
        assert_eq!(
            with_links_module("use crate::wiring::sensor::{Input, Out};\n").as_deref(),
            Some("use crate::links::sensor::{Input, Out};\n")
        );
        // Prose and other names stay.
        assert_eq!(
            with_links_module("// rewiring the wiring; let wiring = 1;\n"),
            None
        );
        assert_eq!(with_links_module("use crate::links::Msg;\n"), None);
    }

    #[test]
    fn wire_tables_become_links() {
        assert_eq!(with_links("[[link]]\nfrom = \"a\"\n"), None);
        assert_eq!(
            with_links("# [[wire]] in a comment stays\n[[wire]]\nfrom = \"a\"\n").as_deref(),
            Some("# [[wire]] in a comment stays\n[[link]]\nfrom = \"a\"\n")
        );
    }

    fn flags(s: &str) -> Vec<String> {
        s.split_whitespace().map(str::to_string).collect()
    }

    #[test]
    fn edge_flags_take_values_and_refuse_a_missing_one() {
        let err = edge_table("udp", &flags("--bind --to 0.0.0.0:14560")).unwrap_err();
        assert_eq!(err, "--bind takes an address (like 0.0.0.0:6969), got --to");
        let err = edge_table("udp", &flags("--bind")).unwrap_err();
        assert_eq!(
            err,
            "--bind takes an address (like 0.0.0.0:6969), got nothing"
        );
        let err = edge_table("udp", &flags("0.0.0.0:6969")).unwrap_err();
        assert!(
            err.starts_with("expected --key, got \"0.0.0.0:6969\""),
            "{err}"
        );

        let t = edge_table(
            "udp",
            &flags("--bind 0.0.0.0:14560 --reply --join 239.2.3.1 --join 239.2.3.2"),
        )
        .unwrap();
        assert_eq!(
            t.to_string(),
            "kind = \"udp\"\nbind = \"0.0.0.0:14560\"\nreply = true\njoin = [\"239.2.3.1\", \"239.2.3.2\"]\n"
        );
        let t = edge_table("serial", &flags("--device /dev/serial0 --baud 9600")).unwrap();
        assert_eq!(t.get("baud").and_then(Item::as_integer), Some(9600));
    }

    #[test]
    fn units_are_imported_once_when_a_field_uses_one() {
        assert!(uses_units("Celsius") && uses_units("Vec<Meters>") && uses_units("Option<Knots>"));
        assert!(!uses_units("f32") && !uses_units("CelsiusReading"));
        let old = "//! doc\n//! more\n\n// bonsai:message\n";
        let new = with_units_import(old).unwrap();
        assert_eq!(
            new,
            "//! doc\n//! more\n\n#[allow(unused_imports)] // units (`temp: Celsius`), here and in every branch\n\
             pub use crate::bonsai::units::*;\n\n// bonsai:message\n"
        );
        assert_eq!(with_units_import(&new), None);
    }

    #[test]
    fn every_unit_is_in_the_runtime() {
        for unit in UNITS {
            assert!(RUNTIME.contains(&format!("unit!({unit}, ")), "{unit}");
        }
        assert_eq!(RUNTIME.matches("    unit!(").count(), UNITS.len());
    }

    #[test]
    fn macro_use_is_added_once() {
        let old = "//! doc\n\nmod bonsai;\nmod branches;\n";
        let new = with_macro_use(old).unwrap();
        assert_eq!(new, "//! doc\n\n#[macro_use]\nmod bonsai;\nmod branches;\n");
        assert_eq!(with_macro_use(&new), None);
        assert_eq!(with_macro_use("mod branches;\n"), None);
        assert_eq!(
            with_macro_use("mod bonsai;"),
            Some("#[macro_use]\nmod bonsai;".into())
        );
    }

    #[test]
    fn arms_match_their_variant_only() {
        assert!(is_input_arm("            Input::Beat(_beat) => {}", "Beat"));
        assert!(is_input_arm("Input::Beat(b) => {", "Beat"));
        assert!(!is_input_arm("Input::BeatTwice(b) => {}", "Beat"));
        assert!(is_input_arm("    Input::Tick => {}", "Tick"));
        assert!(is_input_arm("Input::Tick | Input::Beat(_) => {}", "Tick"));
        assert!(!is_input_arm("Input::TickTock(_) => {}", "Tick"));
        assert_eq!(
            arm("RouteFollow"),
            "Input::RouteFollow(_route_follow) => {}"
        );
        assert_eq!(arm("Beacon"), "Input::Beacon(_beacon) => {}");
        assert_eq!(arm("Tick"), "Input::Tick => {}");
    }

    #[test]
    fn link_args_split_on_the_message_name() {
        let args = |a: &[&str]| a.iter().map(|s| s.to_string()).collect::<Vec<_>>();
        let a = args(&["Reading", "display", "log"]);
        assert_eq!(split_link_args(&a), (Some("Reading"), &a[1..]));
        let a = args(&["planner"]);
        assert_eq!(split_link_args(&a), (None, &a[..]));
    }

    #[test]
    fn message_structs_round_trip() {
        let base = "//! doc\n\n// bonsai:message\n";
        let with = crate::insert_before_marker(
            Path::new(MESSAGES),
            base.to_string(),
            MESSAGE_MARKER,
            &(message_struct("Reading", &[("temp".into(), "f32".into())]) + "\n"),
        );
        assert_eq!(
            with,
            "//! doc\n\n#[derive(Clone, Debug)]\npub struct Reading {\n    pub temp: f32,\n}\n\n// bonsai:message\n"
        );
        let with_two = crate::insert_before_marker(
            Path::new(MESSAGES),
            with.clone(),
            MESSAGE_MARKER,
            &(message_struct("Beat", &[]) + "\n"),
        );
        assert_eq!(graph::parse_messages(&with_two), ["Reading", "Beat"]);
        assert_eq!(without_struct(&with_two, "Beat").unwrap(), with);
        assert_eq!(without_struct(&with, "Reading").unwrap(), base);
        assert!(without_struct(&with, "Read").is_none());
    }
}
