//! The links between branches and edges.
//!
//! Generated by `bonsai sync` from bonsai.toml and src/messages.rs. Don't edit
//! it: change those, then run `bonsai sync` (every bonsai command that changes
//! the graph runs it for you).
#![allow(dead_code, unused_imports, unused_variables)]
#![allow(clippy::enum_variant_names, clippy::wrong_self_convention)]

use std::collections::VecDeque;

use tokio::sync::mpsc;

use crate::bonsai::{EdgeOut, Event, Sends, Slot, Tree, drain, spawn_edge};
use crate::branches;
use crate::messages::*;

/// What each edge hands the core.
#[derive(Debug)]
pub enum EdgeIn {
}

/// Every message in flight: one variant per link.
#[derive(Debug)]
pub enum Msg {
}

/// The run logs to keep, from [record].
const RECORD_CONFIG: crate::bonsai::record::Config = crate::bonsai::record::Config {
    dir: "logs",
    events: true,
    panics: true,
    errors: false,
    edges: false,
    keep_runs: 100,
    keep_days: 0,
    max_file_kb: 10240,
};

/// The links, in bonsai.toml order (from, message, to): for `bonsai top`.
const LINKS: &[crate::bonsai::stats::LinkInfo] = &[
];

/// Every branch and edge, set up and waiting for events.
pub struct Core {
    queue: VecDeque<Msg>,
}

impl Core {
    pub fn new() -> Self {
        crate::bonsai::stats::links(LINKS);
        crate::bonsai::record::configure(RECORD_CONFIG);
        Core {
            queue: VecDeque::new(),
        }
    }

    /// Hand one message to every branch or edge linked to it, in
    /// bonsai.toml's order.
    fn deliver(&mut self, message: Msg, queue: &mut VecDeque<Msg>) {
        match message {
        }
    }
}

impl Default for Core {
    fn default() -> Self {
        Self::new()
    }
}

impl Tree for Core {
    type EdgeIn = EdgeIn;

    fn rates(&self) -> Vec<(usize, f64)> {
        vec![]
    }

    fn start_edges(&mut self, events: &mpsc::Sender<Event<EdgeIn>>) {
        let _ = events;
    }

    fn handle(&mut self, event: Event<EdgeIn>) {
        let mut queue = std::mem::take(&mut self.queue);
        match event {
            Event::Tick(_) => {}
        }
        drain(&mut queue, |message, queue| self.deliver(message, queue));
        self.queue = queue;
    }
}
