//! The wiring between branches and edges.
//!
//! Generated by `bonsai sync` from bonsai.toml and src/messages.rs. Don't edit
//! it: change those, then run `bonsai sync` (every bonsai command that changes
//! the graph runs it for you).
#![allow(dead_code, unused_imports, unused_variables)]
#![allow(clippy::enum_variant_names, clippy::wrong_self_convention)]

use std::collections::VecDeque;

use tokio::sync::mpsc;

use crate::bonsai::{EdgeOut, Event, Sends, Slot, Tree, drain, spawn_edge};
use crate::branches;
use crate::messages::*;

/// What each edge hands the core.
#[derive(Debug)]
pub enum EdgeIn {
}

/// Every message in flight: one variant per wire.
#[derive(Debug)]
pub enum Msg {
}

pub mod pulse {
    use super::*;

    /// What pulse receives.
    #[derive(Debug)]
    pub enum Input {
        /// Its `rate` ticked.
        Tick,
    }

    /// Where pulse sends: `out.send(message)`, `out.to_<edge>(..)`.
    #[derive(Debug, Default)]
    pub struct Out {
        pub(super) sent: Vec<Msg>,
    }

    impl Out {
        /// Send `message` down its wire. Only what pulse is wired to send
        /// compiles.
        pub fn send<M>(&mut self, message: M)
        where
            Self: Sends<M>,
        {
            Sends::send(self, message);
        }

        /// Everything sent so far, oldest first: for tests.
        pub fn sent(&self) -> &[Msg] {
            &self.sent
        }
    }
}

/// Every branch and edge, set up and waiting for events.
pub struct Core {
    pulse: Slot<branches::pulse::Pulse>,
    queue: VecDeque<Msg>,
}

impl Core {
    pub fn new() -> Self {
        Core {
            pulse: Slot::new("pulse"),
            queue: VecDeque::new(),
        }
    }

    /// Hand one message to every branch or edge wired to it, in
    /// bonsai.toml's order.
    fn deliver(&mut self, message: Msg, queue: &mut VecDeque<Msg>) {
        match message {
        }
    }
}

impl Default for Core {
    fn default() -> Self {
        Self::new()
    }
}

impl Tree for Core {
    type EdgeIn = EdgeIn;

    fn rates(&self) -> Vec<(usize, f64)> {
        vec![(0, 2.0)]
    }

    fn start_edges(&mut self, events: &mpsc::Sender<Event<EdgeIn>>) {
        let _ = events;
    }

    fn handle(&mut self, event: Event<EdgeIn>) {
        let mut queue = std::mem::take(&mut self.queue);
        match event {
            Event::Tick(0) => queue.extend(self.pulse.process(pulse::Input::Tick).sent),
            Event::Tick(_) => {}
        }
        drain(&mut queue, |message, queue| self.deliver(message, queue));
        self.queue = queue;
    }
}
